### ISSUE TITLE
Hacs integration

### ISSUE THREAD

**Issue by Nizm0** [PiotrMachowski/Lovelace-Xiaomi-Vacuum-Map-card#1]
Integration with HACS is not working for me
I received error while trying add it to Custom Repositories:
"PiotrMachowski/Home-Assistant-Lovelace-Xiaomi-Vacuum-Map-card - No acceptable js files found"

**Comment by PiotrMachowski** [comment]
There was a problem with a name of the repository. Card should be now available in HACS right now.
https://github.com/custom-components/hacs/pull/305

**Comment by Heisenberg2980** [comment]
I cannot find this card in HACS, has it been removed?

**Comment by PiotrMachowski** [comment]
Nope, it's still there :) in frontend section

**Comment by Heisenberg2980** [comment]
Found it!! Thank you very much, maybe the Installation section could be updated to mention HACS to help not specially awake people (like me today)

**Comment by Heisenberg2980** [comment]
@PiotrMachowski after installing the card in HACS and restart HA multiple times, I am still getting the error "Custom element doesn't exist: xiaomi-vacuum-map-card", is there any other step required after installing it in HACS?

![image](https://user-images.githubusercontent.com/58039006/135733638-ea19f319-97e8-4e6a-9bf0-07ef1799131c.png)

**Comment by Heisenberg2980** [comment]
> @PiotrMachowski after installing the card in HACS and restart HA multiple times, I am still getting the error "Custom element doesn't exist: xiaomi-vacuum-map-card", is there any other step required after installing it in HACS?
> 
> ![image](https://user-images.githubusercontent.com/58039006/135733638-ea19f319-97e8-4e6a-9bf0-07ef1799131c.png)

Answering my own question, I just had to refresh the page and it works now (definitely it is time to go to sleep...)

**Comment by PiotrMachowski** [comment]
@Heisenberg2980 yup, you have to add it to resources. 

```yaml
url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
type: module
```
