### ISSUE TITLE
Card is inactive until another vacuum-card is clicked

### ISSUE THREAD

**Issue by oakhill87** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#100]
The map card remains inactive until another card is clicked.

- Card is non-selectable
- The pull-down meny is listed as an object, not a pulldown menu.
- Cannot select any of the objects until the control-card is clicked. Then the pulldown menu reverts to how it should be.

Here's a video:
https://user-images.githubusercontent.com/43674572/111797447-75bc2280-88c9-11eb-9490-f864f9b016b4.mp4

**Comment by carvalr** [comment]
Same behavior here.
I have to activate the Lovelace setup, no changes on card itself, and then I can use the card after this.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
