### ISSUE TITLE
map trimming

### ISSUE THREAD

**Issue by chikehe** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#101]
it would be great if the map from xiaomi vacuum map extractor can be trimmed here as well

**Comment by PiotrMachowski** [comment]
Is it really needed when you can do it directly in the extractor?

**Comment by chikehe** [comment]
> Is it really needed when you can do it directly in the extractor?

then maybe i missed sth: are the map_transformation parameters from extractor applicable under map_camera?

**Comment by PiotrMachowski** [comment]
No, no, I'm talking about map's configuration

**Comment by chikehe** [comment]
> No, no, I'm talking about map's configuration

but theres no way to use that transformed result in map_camera right?

**Comment by PiotrMachowski** [comment]
You can configure it in [camera's configuration](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration) and use this camera in this card

**Comment by chikehe** [comment]
i see, but wouldnt it be easier to try and test trimming in ui?

**Comment by PiotrMachowski** [comment]
You can disable trimming, calculate how much you want it to be trimmed (these values are just simple percents) and enable it again. Doing it in UI would put unnecessary load on server (trimmed pixels don't need to be processed at this moment) and network (bigger image would need to be sent)
