### ISSUE TITLE
Create cards using the lovelace UI

### ISSUE THREAD

**Issue by mbriney** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#102]
Is it possible to add the xiaomi to the lovelace using the GUI builder?  I am not seeing it come up as an option but I do have it properly added in the resources.

**Comment by PiotrMachowski** [comment]
This card doesn't have a UI editor, you have to configure it in yaml

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
