### ISSUE TITLE
Lovelace card not working

### ISSUE THREAD

**Issue by dogmatic69** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#107]
Used the config from the readme I get the following: (installed with HACS)

```
Custom element doesn't exist: xiaomi-vacuum-map-card.
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum
map_image: /local/custom_lovelace/xiaomi_vacuum_map_card/map.png
...
```

Looking in the custom folder there does not seem to be anything related to this card. I've tried reinstalling multiple times and still the same.

**Comment by PiotrMachowski** [comment]
How have you installed this card?

**Comment by PiotrMachowski** [comment]
Have you added this card to resources?
If so, what path have you used?

**Comment by kamwill** [comment]
I have the same issue - used path "/local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js"

**Comment by dogmatic69** [comment]
it was various user errors, now working though.

**Comment by PiotrMachowski** [comment]
@kamwill You have to use following path in resources when installed via HACS:
```
/hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
```
