### ISSUE TITLE
Not available on HACS anymore?

### ISSUE THREAD

**Issue by plumped** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#109]
I can't find de custom card anymore in HACS, and if i try to add it manually i get the error message "Custom element doesn't exist: xiaomi-vacuum-map-card" do you have any idea?

**Comment by plumped** [comment]
Im an idiot....

**Comment by Heisenberg2980** [comment]
I think I am an idiot as well because I cannot find this card in HACS, should it be there? The installation instructions just mention the manual method (i.e. Add the card to resources in ui-lovelace.yaml or in the raw editor if you are using the frontend UI editor)

**Comment by PiotrMachowski** [comment]
It's definitely still there (in Frontend section)
