### ISSUE TITLE
Supoort for Hacky Home assistant support for Xiaomi vacuum STYJ02YM

### ISSUE THREAD

**Issue by balkonrad** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#115]
HI, I'm using [this integration](https://github.com/nqkdev/home-assistant-vacuum-styj02ym) to have my STYJ02YM working. 
Your add-on works in the sense that you can add it to the UI, while sending the robot to the area or trying to clean ends with the message "Command sent" and that's it.

Here's the log:

```
Logger: custom_components.miio2.vacuum
Source: custom_components/miio2/vacuum.py:294
Integration: miio2 (documentation)
First occurred: 15:58:38 (2 occurrences)
Last logged: 15:59:12

Unable to send command to the vacuum: No response from the device
```

It is possible to make this working?

**Comment by PiotrMachowski** [comment]
Currently this card doesn't support Viomi/STYJ02YM vacuums, it should be added soon (#114)

**Comment by al-one** [comment]
[hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot) support viomi and roborock vacuum for this card.

https://github.com/al-one/hass-xiaomi-miot/commit/214c2d01c5e270e6bb2bbd53b24c5287917c4c65
https://github.com/al-one/hass-xiaomi-miot/commit/9a4f4c519af832ef6a8396d51009cba4ec4fb3c3

**Comment by hank-droid** [comment]
> [hass-xiaomi-miot](https://github.com/al-one/hass-xiaomi-miot) support viomi and roborock vacuum for this card.
> 
> [al-one/hass-xiaomi-miot@214c2d0](https://github.com/al-one/hass-xiaomi-miot/commit/214c2d01c5e270e6bb2bbd53b24c5287917c4c65) [al-one/hass-xiaomi-miot@9a4f4c5](https://github.com/al-one/hass-xiaomi-miot/commit/9a4f4c519af832ef6a8396d51009cba4ec4fb3c3)

i selected the vacuum entity via the miot integration and  i get the following error message on lovelace
"Failed to call service vacuum/send_command. not a valid value for dictionary value @ data['entity_id']"

**Comment by honkerst** [comment]
I've just encountered this issue too, looking forward to support for the Mop Pro STYJ02YM. 

In the meantime I've just added individual buttons for each room, this service call works for the Mop Pro:

```
service: vacuum.xiaomi_clean_zone
data: {
  "entity_id": "vacuum.robomop",
  "zone": [[4.7, -1.45, 10.6, 1.15]],
  "repeats": 1
}
```

The HA script looks like this:

  ```
vacuum_living_room:
      alias: "Vacuum the Living Room"
      sequence:
        - service: vacuum.xiaomi_clean_zone
          data:
            entity_id: vacuum.robomop
            repeats: 1
            zone: [[4.7, -1.45, 10.6, 1.15]]
```

I do miss the Map Card's ability to select multiple rooms and tap the start button though! It was my most used card! (I have another older Xiaomi vacuum which I've now moved upstairs that works perfectly with it) Thanks!

**Comment by PiotrMachowski** [comment]
New version should be published really soon!

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
