### ISSUE TITLE
HA companion app (android) is not displaying the map 

### ISSUE THREAD

**Issue by fokcuk** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#116]
Hello.
From the browser it works fine. When viewing via the companion app on Android I get this error instead of the image:

Custom element doesn't exist: xiaomi-vacuum-map-card

**Comment by PiotrMachowski** [comment]
Everything should work in HA app as well. Try reloading resources and clearing cache

**Comment by fokcuk** [comment]
thank you. took few attempts but worked eventually =)
now have to work out how to make spot/zone cleaning from the card with my Viomi

**Comment by PiotrMachowski** [comment]
Viomi doesn't work at this moment ;)
