### ISSUE TITLE
Feature Request: Ability to send xiaomi on a pre determined path

### ISSUE THREAD

**Issue by ctrl50** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#117]
So we are able to 'go to target' which by the way, you can adjust the vacuum suction while its 'going to the target' which is basically sending it on a path vacuuming. 

IT would be nice to be able to draw a path on the map and have it follow the path. 

say you wanted vaccum along a certain wall, and then around a table etc... it would be similar to zones, but without teh square area.

it should be possible right? we have all the coordinates, we have the map. we can send it on its way while vaccuming.

Wish I had more programming knowledge to help, but hey its an idea!

thanks.

**Comment by PiotrMachowski** [comment]
It is not easily achievable, because vacuum receives only one coordinate pair at a time. It would require a script that waits until the vacuum will reach a desired place and then send it to a next point

**Comment by ctrl50** [comment]
Sorry for the wrong place, 

Hmm. interesting. So its a point to point system. sounds like alot to code but still maybe do-able. im thinking like how you select a point on the map , then select the next point, etc.. each time that would build the path.. wish I was better at this stuff haha.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0

**Comment by ctrl50** [comment]
Nice! Can't wait to try it soon (Out of town, on work for a few more days) 

Thanks!
