### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by xLoGiiKzZo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#12]
I have a paid inquiry for the creator of this project. I haven't been able to find any way to contact you, therefore, I decided I'd give this place a try.

Please contact me at: private@dannyschmickler.me if you're interested.

**Comment by PiotrMachowski** [comment]
I have sent you an email, you can also find me on Home Assistant forum: https://community.home-assistant.io/u/3_14
