### ISSUE TITLE
Issue with zones and go to commands

### ISSUE THREAD

**Issue by Wombosvideo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#124]
Whenever I try to select a spot on the map fetched by [xiaomi map extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) and select the go to command home assistant notifies me that a command was sent to my rockrobo but it won't execute the commands.

Either the commands are faulty (i.e. using the wrong arguments) or my Xiaomi Mi Robot for some reason doesn't support them or has a different command for that. I am able to perform these actions in the Mi Home app so the issue either comes from [xiaomi map extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) or this lovelace card integration.

Does anyone else have this issue? Hit thumbs up. Does anyone have a fix to this? Hit me up.

**Comment by PiotrMachowski** [comment]
Extractor doesn't send any commands to a vacuum. What is a model of your vacuum? Do you have anything in logs?

**Comment by SunilKhusal** [comment]
I have the exact same problem as described above. Name: "Mi Robot Vacuum-Mop P" Model: "STYTJo2YM"

The following is the 5 warnings/errors I get on the logs:
--------------------------
Logger: homeassistant.components.camera
Source: components/camera/__init__.py:569
Integration: Camera (documentation, issues)
First occurred: 1:50:50 AM (7 occurrences)
Last logged: 1:51:18 AM

The websocket command 'camera_thumbnail' has been deprecated
--------------------------
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:693
Integration: Camera (documentation, issues)
First occurred: 1:50:51 AM (4 occurrences)
Last logged: 1:51:21 AM

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
--------------------------
Logger: miio.miioprotocol
Source: /usr/local/lib/python3.9/site-packages/miio/miioprotocol.py:240
First occurred: 1:51:21 AM (1 occurrences)
Last logged: 1:51:21 AM

Got error when receiving: timed out
--------------------------
This error originated from a custom integration.

Logger: custom_components.miio2.vacuum
Source: custom_components/miio2/vacuum.py:261
Integration: miio2 (documentation)
First occurred: 1:51:21 AM (1 occurrences)
Last logged: 1:51:21 AM

Unable to send command to the vacuum: No response from the device
--------------------------
Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:693
Integration: Camera (documentation, issues)
First occurred: 1:50:51 AM (34 occurrences)
Last logged: 1:56:22 AM

Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
--------------------------

My Card Configuration:

```
type: custom:xiaomi-vacuum-map-card
entity: vacuum.mi_vacuum
map_camera: camera.xiaomi_cloud_map_extractor
camera_calibration: true
zones:
  - - - 1
      - -6
      - 5
      - -2
      - 1

```

**Comment by PiotrMachowski** [comment]
@SunilKhusal your model is currently not supported, you can use [this version](https://github.com/halfbakery/lovelace-xiaomi-vacuum-map-card/tree/viomi_support) of a card
