### ISSUE TITLE
Vacuum map card doesn't work properly

### ISSUE THREAD

**Issue by Jese44** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#125]
Map shows vacuum location, areas, traces etc ok, but whenever i draw zone to be cleaned, it does draw the area to the map but when i press start, it does nothing. No idea when this problem started since i have not used zone cleanup for a while... 
Also when pressing start, the card indicates "command sent!"
Same problem with go to target... 
I know i have updated HA to the most recent version, but i have no idea has there been auto updates to the vacuum and/or xiaomi home app in my phone...

No idea how to troubleshoot this.

**Comment by PiotrMachowski** [comment]
Was it working before?

What vacuum model do you have?

**Comment by Jese44** [comment]
Yes, it worked before, last time i used it was like 3-4 months ago. now i tried to use the zoned cleanup, but with no luck

s5Max

**Comment by PiotrMachowski** [comment]
You probably have `entity does not exists` in HA logs. To fix it you have to remove the vacuum from configuration.yaml

**Comment by Jese44** [comment]
Which log to be exact?
And should i move them to elsewhere or just remove? are they generated automatically somewhere?
I have it as follows in the configuration.yaml:
vacuum
  - platform: xiaomi_miio
    entity_id: vacuum.xiaomi_vacuum_cleaner
    name: "vacuumname"
    host: ip.ip.ip.ip
    token: !secret tokenname

**Comment by Jese44** [comment]
Something i found in logs:
unable to find reference entities vacuum.vacuumname
update of camera.vacuumname is taking over 10 seconds
Error unloading entry vacuum name for xiaomi_miio

**Comment by Jese44** [comment]
Sorry to spam this thread, but removing the vacuum from configuration.yaml worked, but i can't understand how/why, could you give a simple explanation please?

**Comment by PiotrMachowski** [comment]
Yup, you have to remove it from configuration.yaml. Since 2021.7 Xiaomi Vacuums are configured using UI
