### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by Quentin-Cloos** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#126]
Hello, I'm not new in Home Assistant but I can't figure it out why I have this error:

```
Custom element doesn't exist: xiaomi-vacuum-map-card.
type: custom:xiaomi-vacuum-map-card
entity: vacuum.xiaomi_vacuum
map_camera: camera.xiaomi_cloud_map_extractor
camera_calibration: true
```

I have uploaded all the files in /local/custom_lovelace/xiaomi_vacuum_map_card/ and I have added it in resources, nothing in the logs.

Anyone can help? Thank you in advance!

**Comment by PiotrMachowski** [comment]
I highly recommend HACS, it will do everything for you.

If you want to do it manually you have to save files in ` /www/custom_lovelace/xiaomi_vacuum_map_card/`, `local` is an "alias" for `www` in resources

**Comment by Quentin-Cloos** [comment]
Thanks and sorry! I didn't found the integration in the first place, but now it's working with HACS, thanks again! it's a great and usefull tool.

**Comment by PiotrMachowski** [comment]
No problem :)
