### ISSUE TITLE
js working only if I put the files only in {config}/www folder, not below

### ISSUE THREAD

**Issue by cova-fe** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#127]
Hi, I'm giving a try to this card (thanks for the effort!) but I have an issue, likely due to my inexperience with HA.
I followed the instructions, but placing js files under www/custom_lovelace/xiaomi_vacuum_map_card/ will not work. To make the card work, I have to put the files straight under the first level (www/). Any other level will not work, even though the file is accessible via /local/... url.
I'm pretty sure I'm doing something wrong, but not sure what.

**Comment by PiotrMachowski** [comment]
@cova-fe have you tried v2?
