### ISSUE TITLE
The card is not compatible with a dark theme

### ISSUE THREAD

**Issue by mkowalczuk** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#131]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The card doesn't work well with [Hass Synthwave](https://github.com/bbbenji/synthwave-hass) theme. Some of the buttons are barely visible. I'm not sure if that's an issue of the theme or of Xiaomi Vacuum Map card, but I haven't noticed a similar issue with other 3rd party or built-in cards.

(Please ignore lack of the actual map on the screenshot. The map shows just fine, I panned it to hide my home layout.)

![Screenshot from 2021-11-15 17-24-15](https://user-images.githubusercontent.com/187606/141818348-4346b2f5-812f-4a59-ad23-2bb2b881ec2d.png)

### What version of a card has described problem?

v2.0.0

### What was the last working version card?

v1.x

### What vacuum model do you have problems with?

roborock.vacuum.s5e

### What version of Home Assistant do you use?

core-2021.11.1

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
The card is designed to work with built-in themes. You can use [these css variables](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/css_variables.md) to adjust your custom theme
