### ISSUE TITLE
Script from follow_path.yaml does not match actual service call

### ISSUE THREAD

**Issue by giu889** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#133]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Thank you for the big update.

There is a small issue that might confuse new users. The path function throws an error with the script from `follow_path.yaml` you provide:

> Fehler beim Aufrufen des Diensts script/vacuum_follow_path. Service not found.

Renaming the script from `follow_path` to `vacuum_follow_path` fixes the issue.

### What version of a card has described problem?

v2.0.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

core-2021.11.3

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
You are right. Thank you!

I have renamed the script
