### ISSUE TITLE
Card only show Status, Battery and Fan speed. Not show filter, sensors, main brush and more.

### ISSUE THREAD

**Issue by fbirollo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#135]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The card only show some information. Doesn't show Main Brush or filter or sensors information.

Can you help me?
![captura](https://user-images.githubusercontent.com/30130311/141855686-a14b0791-6a29-49da-8289-90123735c5e2.png)

### What version of a card has described problem?

2.0.1

### What vacuum model do you have problems with?

roborock.vacuum.s5

### What version of Home Assistant do you use?

2021.11.3

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
You have to enable appropriate sensors in settings of miio integration in HA.

**Comment by fbirollo** [comment]
You are the chosen one.

**Comment by maciejkrasuski** [comment]
Here you can find this config:
![image](https://user-images.githubusercontent.com/70077751/141860176-50beb62e-b9b0-4b7b-8e35-b4e8046e09c5.png)
