### ISSUE TITLE
Live Maps

### ISSUE THREAD

**Issue by sendorm** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#15]
I have updated my configuration to include live maps view through https://github.com/asphalter/xiaomi_vacuum with a rooted vacuum -which by the way was no way an hustle-. 
It creates a "navmap.png" file under local folder, which updates whenever the vacuum moves. 
If I include that image in the lovelace-xiaomi-vacuum-map-card config, it just caches an old picture and does not update as expected. 
If the ability to update the image of this custom card just as "local_file" camera component does is included in this component, it would make the integration complete. 
This of course is not an issue but a feature request. Thanks for the great work.

**Comment by PiotrMachowski** [comment]
This is a direction I have in mind sice the beginning of this card. I have to finally root my vacuum and get it done, but it will definitely take some time.

**Comment by sendorm** [comment]
You can also check this out:
https://github.com/pheuzoune/ha_xiaomi_vacuum_map

**Comment by PiotrMachowski** [comment]
Thanks, I am familiar with these solutions, but I'm afraid I will have to make a dedicated integration to provide a way to autocalibrate a map.

**Comment by sendorm** [comment]
Great. Waiting for a solution. Thank you.

**Comment by darkkatarsis** [comment]
Exactly, such functionality is missing.
I have question, is it possible to add as map_image entity like camera instead of png?

something like that:
entity: camera.rockrobo_map
camera_view: live

**Comment by PiotrMachowski** [comment]
I have rooted my vacuum yesterday, so I can start working on a new version of a card.
@darkkatarsis it should be possible, but I have to make some more research

**Comment by PiotrMachowski** [comment]
@sendorm @darkkatarsis 
In release v1.1.0 I have added possibility to use camera feed as a background. I will try to add autocalibration in future releases

**Comment by sendorm** [comment]
I've checked the camera functionality and it's working. Thank you.

**Comment by darkkatarsis** [comment]
@PiotrMachowski The camera works very well, thank you for the quick enhancement of functionality. I noticed that after browser refresh map needs a few seconds before it appears by itself (I suspect that as long as the interval is set). Unless you click on it or wait - then it appears, which means it is already generated. Can anything be done about it?

![ezgif-6-85c441777004](https://user-images.githubusercontent.com/24244919/68455743-610f4b00-01fc-11ea-87fa-81245daddb2c.gif)

**Comment by Domy5** [comment]
> @PiotrMachowski The camera works very well, thank you for the quick enhancement of functionality. I noticed that after browser refresh map needs a few seconds before it appears by itself (I suspect that as long as the interval is set). Unless you click on it or wait - then it appears, which means it is already generated. Can anything be done about it?
> 
> ![ezgif-6-85c441777004](https://user-images.githubusercontent.com/24244919/68455743-610f4b00-01fc-11ea-87fa-81245daddb2c.gif)

wow how that image is made
