### ISSUE TITLE
Appending tiles

### ISSUE THREAD

**Issue by Nicholaiii** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#150]
### Description

It would be really sweet if we could define additional tiles in the global scope, that does not override the existing tiles. 

### Solution

A bool to include default tiles, or alternatively a secondary list of tiles to add.

### Context

I really love this new update, this allows me to skip using `xiaomi-vacuum-card`, and hopefully soon, the entire rest of my vacuum related controls

**Comment by PiotrMachowski** [comment]
Yeah, I think it will be useful

**Comment by PiotrMachowski** [comment]
Resolved in v2.0.2
