### ISSUE TITLE
The option to hide tiles and Icon list entry options

### ISSUE THREAD

**Issue by thijselblaso** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#155]
### Description

I like to have the option to hide the tiles and icon list entry options.

![Screenshot 2021-11-16 at 14 49 28](https://user-images.githubusercontent.com/38098396/141997359-89b72652-f9df-44a0-9e80-9472a2c15487.png)

### Solution

Add option to hide the tiles and icon list entry options.

![Screenshot 2021-11-16 at 14 48 50](https://user-images.githubusercontent.com/38098396/141997205-7afe2a94-de79-46c5-a07e-1a943c543894.png)

**Comment by PiotrMachowski** [comment]
It is already possible. You just have to use following config:
```yaml
icons: []
tiles: []
```
