### ISSUE TITLE
New version of card - Live maps

### ISSUE THREAD

**Issue by darkkatarsis** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#16]
@PiotrMachowski The camera works very well, thank you for the quick enhancement of functionality. I noticed that after browser refresh map needs a few seconds before it appears by itself (I suspect that as long as the interval is set). Unless you click on it or wait - then it appears, which means it is already generated. Can anything be done about it?

![ezgif-6-85c441777004](https://user-images.githubusercontent.com/24244919/68455743-610f4b00-01fc-11ea-87fa-81245daddb2c.gif)

alse without popup:

![ezgif-4-1647725a7bcc](https://user-images.githubusercontent.com/24244919/68495764-297ebe00-0251-11ea-8eb9-3f90142bf440.gif)

Addition info: Im using ICantBelieveItsNotValetudo addon with crop settings to generate camera view.

**Comment by darkkatarsis** [comment]
An idea came into my head suddenly. If this is a problem of browser rendering, or the HA camera entity itself, then maybe not the most elegant solution, will be adding a simple click() function after building canvas?

**Comment by PiotrMachowski** [comment]
I have fixed this issue in version v1.1.1
