### ISSUE TITLE
Wrong cords for zone cleaning

### ISSUE THREAD

**Issue by darkkatarsis** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#17]
After calibrate map, goto command works fine with 100% accuracy on the whole map. But with predefined zone its something wrong. 

When using cords from valetudo or FloleVac this cords are shifted on map.
When creating zones using debug map, and save cords from alert window, everything looks good but roborock is missing zones in valetudo.

**Details:**
- Root - Valetudo
- Addon ICantBelieveItsNotValetudo 0.2.0 to generate and crop map and generate camera map

**possible solution**
Make it possible to set the offset for predefined zones by adding x and y attributes, exactly as in the calibration

**Comment by PiotrMachowski** [comment]
That's weird,

**Comment by PiotrMachowski** [comment]
That's weird, as both commands use the same coordinates calculation method. Could you provide a screenshot of shifted predefined zones? It's very probable that simple shift on x and y won't solve this issue.

**Comment by darkkatarsis** [comment]
**Shifted predefined zones (cords are from valetudo and working fine):**
<img width="369" alt="Screenshot 2019-11-09 at 10 52 05" src="https://user-images.githubusercontent.com/24244919/68526725-19152480-02df-11ea-9d7e-8d7e8c60551e.png">

**My code:**
`- type: custom:xiaomi-vacuum-map-card
                    entity: vacuum.xiaomi_vacuum_cleaner
                    map_camera: camera.rockrobo_map
                    camera_refresh_interval: 5
                    debug: true
                    calibration_points:
                      - vacuum:
                          x: 25500
                          y: 25500
                        map:
                          x: 590
                          y: 860
                      - vacuum:
                          x: 23000
                          y: 25500
                        map:
                          x: 398
                          y: 860
                      - vacuum:
                          x: 23000
                          y: 33500
                        map:
                          x: 398
                          y: 225
                    zones:
                      - [[23859, 15350, 28029, 17507], [25150, 17500, 28050, 17900]]
                      - [[24300, 17950, 27800, 21600], [24000, 19750, 24300, 21000], [24600, 17500, 26150, 17950]]
                      - [[23500, 21550, 26277, 22456], [25351, 22458, 26270, 23575]]
                      - [[22289, 15426, 23839, 17126]]
                      - [[21755, 17705, 24578, 18550], [21805, 17338, 24531, 17694], [21901, 16938, 22629, 17332], [22700, 18550, 23950, 20856], [21400, 20850, 23950, 21850], [23950, 18550, 24300, 20450]]`

**Screen one of zone from valetudo:**
Does it look like this zone is turned 180 degrees on lovelace-xiaomi-vacuum-map-card ?
<img width="481" alt="Screenshot 2019-11-09 at 10 54 24" src="https://user-images.githubusercontent.com/24244919/68526764-82953300-02df-11ea-9848-f758baf9cbb2.png">

**Comment by PiotrMachowski** [comment]
I have analyzed your configuration and card is behaving correctly. The issue seems to be with `y` coordinates of your predefined zones (marked as blue): none of them are from the range (25500, 33500), so they are not displayed on your map, but below it. Please take a look at the example:
![image](https://user-images.githubusercontent.com/6118709/68527899-b165d600-02ec-11ea-9958-2ae22e872302.png)
If zoned cleanup and goto both work fine then valetudo does some weird magic with coordinates.

**Comment by darkkatarsis** [comment]
I see, it seems to me that it's related to valetudo and how it generated the map. The fact that the 2nd parameter is bad only confirms that it can be a mirror image. I just wonder that valetudo knows how to interpret it. Anyway, I found a solution by modifying the file in python. Unfortunately, I need a little more time to share it.

Question. Due to the fact that valetudo communicates over mqtt, do you plan to do such card variations? It should be noted that valetudo does not accept parameters but the names of defined zones. Eg.

```
- service: mqtt.publish
   date:
       topic: valetudo / rockrobo / custom_command
       payload: '{"command": "zoned_cleanup", "zone_ids": ["Library"]}'
```

**Comment by PiotrMachowski** [comment]
In your first comment you said:
> When creating zones using debug map, and save cords from alert window, everything looks good but roborock is missing zones in valetudo.
What do you mean by that? If zoned cleanup works correctly predefined zones created using coordinates from debug should also work.

According to mqqt and card variations:
In this case every predefined zone would have to have specified name + other modes should be left unchanged. I am not sure if it is very useful to keep zones defined in both valetudo and this card.
If you want you can use parameter `service` and make card call your own script that can recognise predefined zones calls and replace them with mqqt calls. Example scripts are available in `examples` directory in this repo. Keep in mind that you can't use templates in `params` section. To overcome this issue you can use my python script, also available in `examples`.

**Comment by darkkatarsis** [comment]
I gave up on mqtt, now everything works as it should. If someone insists on using mqtt I wrote a quick workaround for zones. I've never wrote in python so the code is really lame... but works and may help someone. 

```
entity_id = data.get('entity_id')
command = data.get('command')
params = str(data.get('params'))
parsedParams = []
x = []
y = []
flag = False

ini_list = [
            # 1 time
            ["Living room", "[['21070', '24948', '26688', '29561', 1]]"],
            ["Bedroom", "[['23879', '29597', '27833', '33029', 1], ['24396', '33029', '27057', '33459', 1]]"],
            ["Office", "[['23768', '33530', '28129', '35747', 1], ['26355', '33137', '28092', '33530', 1]]"],
            ["Bathroom", "[['22142', '33923', '23805', '35747', 1]]"],
            ["Library", "[['21218', '30562', '22770', '32171', 1]]"],
            ["Hallway", "[['22955', '32279', '24507', '33888', 1], ['21624', '32600', '22918', '34102', 1], ['22622', '29597', '24064', '32279', 1], ['21292', '29561', '22622', '30169', 1]]"],
            # 2 times
            ["Living room", "[['21070', '24948', '26688', '29561', 2]]"],
            ["Bedroom", "[['23879', '29597', '27833', '33029', 2], ['24396', '33029', '27057', '33459', 2]]"],
            ["Office", "[['23768', '33530', '28129', '35747', 2], ['26355', '33137', '28092', '33530', 2]]"],
            ["Bathroom", "[['22142', '33923', '23805', '35747', 2]]"],
            ["Library", "[['21218', '30562', '22770', '32171', 2]]"],
            ["Hallway", "[['22955', '32279', '24507', '33888', 2], ['21624', '32600', '22918', '34102', 2], ['22622', '29597', '24064', '32279', 2], ['21292', '29561', '22622', '30169', 2]]"],
            # 3 times
            ["Living room", "[['21070', '24948', '26688', '29561', 3]]"],
            ["Bedroom", "[['23879', '29597', '27833', '33029', 3], ['24396', '33029', '27057', '33459', 3]]"],
            ["Office", "[['23768', '33530', '28129', '35747', 3], ['26355', '33137', '28092', '33530', 3]]"],
            ["Bathroom", "[['22142', '33923', '23805', '35747', 3]]"],
            ["Library", "[['21218', '30562', '22770', '32171', 3]]"],
            ["Hallway", "[['22955', '32279', '24507', '33888', 3], ['21624', '32600', '22918', '34102', 3], ['22622', '29597', '24064', '32279', 3], ['21292', '29561', '22622', '30169', 3]]"]
            ]

if command == "app_goto_target":
    for z in params.replace(' ', '').replace('],[', '|').replace('[', '').replace(']', '').split('|'):
        rect = []
        for c in z.split(','):
            rect.append(int(c))
        parsedParams.append(rect)
    parsedParams = parsedParams[0]

    hass.services.call('vacuum', 'send_command', {'entity_id': entity_id, 'command': command, 'params': parsedParams}, True)

elif command == "app_zoned_clean":

    for z in params.replace('], [', ']|[').replace(']]', ']').replace('[[', '[').split('|'):
        if str(z) in str(ini_list):
            flag = True

    if flag == True:
        for z in params.replace('], [', ']|[').replace(']]', ']').replace('[[', '[').split('|'):
            if str(z) in str(ini_list):
                z.replace("'", '"')
                for j in ini_list:
                    if z in j[1]:
                        if j[0] not in x:
                            x.append(j[0])

        cords = str(x).replace("'", '"')
        #hass.services.call('system_log', 'write', {'message': cords}, True)
        hass.services.call('mqtt', 'publish', {'topic': 'valetudo/rockrobo/custom_command', 'payload': '{ "command": "zoned_cleanup", "zone_ids":' + cords + '}'}, True)

    else:
        for z in params.replace(' ', '').replace('],[', '|').replace('[', '').replace(']', '').split('|'):
            rect = []
            for c in z.split(','):
                rect.append(int(c))
            parsedParams.append(rect)

        hass.services.call('vacuum', 'send_command', {'entity_id': entity_id, 'command': command, 'params': parsedParams}, True)
```

You can close this issue

**Comment by PiotrMachowski** [comment]
I'm glad you made it work :)

Thanks for attaching your workaround, I will probably try to make it more generic and put it in examples.

PS. I have never written in JavaScript before, yet here I am ;)
