### ISSUE TITLE
Increase room selection limit beyond 5

### ISSUE THREAD

**Issue by dnikles** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#174]
### Description

Currently I can only select 5 rooms to clean at a time when using room cleaning. I usually think of room selection as only needing to clean a few rooms, but it could be useful to clean every room except a specific room, in which case more than 5 rooms may need to be selected. 

### Solution

Increase the number of rooms that may be selected. My use case would be satisfied with 8 but I bet there are others that could use more.

**Comment by PiotrMachowski** [comment]
Are you sure that Xiaomi vacuums support cleaning more than 5 rooms in one go? Can you check it in Xiaomi Home?

**Comment by dnikles** [comment]
Yes it allows me to select more than 5

**Comment by PiotrMachowski** [comment]
Is there any max number of rooms to clean?

**Comment by dnikles** [comment]
You'll need to find someone with a bigger house to answer that! As far as I
can tell there isn't though.

**Comment by PiotrMachowski** [comment]
Resolved in v2.0.2
