### ISSUE TITLE
There is a way to run a script with every start?

### ISSUE THREAD

**Issue by noorbertt** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#180]
### Description

My vacuum has its own garage and if I setup the cleaning process with this 2.0 map the door opening with delay.

### Solution

I would like to run a script before any "go" command. (go to, cleaning, zone cleaning..etc)

**Comment by PiotrMachowski** [comment]
what was your setup for v1?

**Comment by noorbertt** [comment]
I used v1 just for a map. 
Under the map I had a input buttons for do the cleaning commands. 

My second thought is a infra or movement sensor in the vacuum garage.

**Comment by PiotrMachowski** [comment]
This scenario should be handled in a script to make it work correctly. You should create 3 scripts that will act as a proxy: they should receive vacuum service call parameters, open garage and then pass them on to the vacuum.

The other approach (probably simpler) is to use automation that will listen to `call_service` events and open garage if needed:
```json
{
    "event_type": "call_service",
    "data": {
        "domain": "xiaomi_miio",
        "service": "vacuum_clean_zone",
        "service_data": {
            "zone": [
                [
                    24867,
                    26184,
                    27086,
                    28081
                ]
            ],
            "repeats": 1,
            "entity_id": "vacuum.alfred"
        }
    }
}
```

**Comment by noorbertt** [comment]
Thank you,

I found a way:

`trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: xiaomi_miio
      service: vacuum_clean_zone
  - platform: event
    event_type: call_service
    event_data:
      domain: xiaomi_miio
      service: vacuum_goto
  - platform: event
    event_type: call_service
    event_data:
      domain: xiaomi_miio
      service: vacuum_remote_control_start
  - platform: event
    event_type: call_service
    event_data:
      domain: vacuum
      service: start`
