### ISSUE TITLE
Simplification of room cleaning 

### ISSUE THREAD

**Issue by tempmaseg** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#190]
### Description

I love the updated version! Great job!

I started to get the coordinates for one room, but it is quite a time consuming task to get the coordinates. Hence, I am wondering if it is possible to simplify the process by using the initial segmentation done by the vacuum cleaner itself.

### Solution

It is possible to use the initial segmentation done by the vacuum cleaner itself, by calling service XIAOMI_MIIO.VACUUM_CLEAN_SEGMENT with a segment (one or several numbers). Where one number represents one room. 

https://www.home-assistant.io/integrations/xiaomi_miio/#service-xiaomi_miiovacuum_clean_segment

Numbers 1..15 are used to number the initial segmentation done by the vacuum cleaner itself. 
Numbers 16 and upwards numbers rooms from the users manual editing.

https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-room-numbers

**Comment by PiotrMachowski** [comment]
It is already possible: [documentation](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#supported-templates), [example](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/docs/demo_config.yaml#L33)

https://user-images.githubusercontent.com/6118709/141666925-34b01cde-82ff-447b-aecc-e9ced402b1ed.mp4

**Comment by tempmaseg** [comment]
Oh nice, so I just don't add outline and just select the ID as the initial segmentation done by the vacuum cleaner itself?

**Comment by PiotrMachowski** [comment]
It is not mandatory, buy you have to add outline or/and icon to be able to click something to select a room (they are used only to display controls on map, so they don't have to be positioned accurately)

**Comment by tempmaseg** [comment]
Oh, I see. Then I misunderstood. I thought it was the coordinates that defined the zone!

Thanks for the help!
