### ISSUE TITLE
Condition option documentation incomplete

### ISSUE THREAD

**Issue by Nicholaiii** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#195]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

The options for the conditions seems to be incomplete
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#condition-options

### What version of a card has described problem?

2.0.0+

### What vacuum model do you have problems with?

not-applicable

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

-

### What version of Home Assistant do you use?

-

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
Thank you! Fixed
