### ISSUE TITLE
Obraz mapy

### ISSUE THREAD

**Issue by pepeEL** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#20]
Witam
Mam zainstalowany twój dodatek do robota sprzątającego Xiaomi. Powiedz mi w jaki sposób zrobić mape mieszkania żeby dodać w twoim dodatku ?
I potem te punkty calibration_points o co w tym chodzi ? I skąd wziac te punkty ?I jak potem ustawic też strefy-zone ?

**Comment by PiotrMachowski** [comment]
Obraz mapy najlepiej zrobić jako screenshot z aplikacji Xiaomi albo FloleVac.
Kalibracja jest jak na razie najlepiej opisana tutaj: https://community.home-assistant.io/t/xiaomi-vacuum-interactive-map-card/123901/196
Polecam też przeglądnięcie dyskusji, dużo problemów zostało tam rozwiązanych.

**Comment by pepeEL** [comment]
Tylko mapa w aplikacji jest taka zlej jakości a u Ciebie jest w idealnej jakości....?

**Comment by pepeEL** [comment]
I czy da sie jakoś to pogodzić jak mam w domu parter i piętro ?

**Comment by PiotrMachowski** [comment]
Swoją mapę poprawiłem w GIMPie, usuwając z niej wszystkie niedoskonałości.
Co do pięter, to byś musiał zrobić 2 karty z osobnymi mapami, jeśli odkurzacz za każdym razem będzie generował takie same mapy dla każdego z pięter.

**Comment by pepeEL** [comment]
Niestety piętra są ciut inne...

czw., 21 lis 2019, 15:58 użytkownik Piotr Machowski <
notifications@github.com> napisał:

**Comment by PiotrMachowski** [comment]
Miałem na myśli, że jeśli odkurzacz ogarnie, że jest na "innym terenie" i odpowiednio przełączy mapę. Nie używałem nigdy odkurzacza na wielu piętrach, także ciężko mi cokolwiek powiedzieć. Obawiam się, że może jednak tego nie ogarnąć.

**Comment by pepeEL** [comment]
No właśnie ciekawe czy da się używać tego odkurzacza na dwóch poziomach
domu.

czw., 21 lis 2019, 20:58 użytkownik Piotr Machowski <
notifications@github.com> napisał:
