### ISSUE TITLE
Question about the map position

### ISSUE THREAD

**Issue by lbouriez** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#21]
Hello, I got how to find the actual position using flolevac but how do I find the map position ?

**Comment by PiotrMachowski** [comment]
Hi, the easiest way is to use Paint or any other image editor.
Paint:
![image](https://user-images.githubusercontent.com/6118709/69348153-fe936180-0c75-11ea-92d3-fb0caf9d2be2.png)
GIMP:
![image](https://user-images.githubusercontent.com/6118709/69348288-39959500-0c76-11ea-86ab-1d8159327891.png)

**Comment by lbouriez** [comment]
Ok, thx very much
