### ISSUE TITLE
Broken link to style.js in README.md

### ISSUE THREAD

**Issue by elipinska** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#22]
Just noticed the link to style.js in the [README.md](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/README.md) file is currently broken -- I believe it should point to https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/dist/style.js

**Comment by PiotrMachowski** [comment]
Thank you, I have fixed the link.

**Comment by elipinska** [comment]
Excellent, thank you -- amazing job on this by the way, works like a charm and has saved me from having to root my vacuum to get what I need!

**Comment by PiotrMachowski** [comment]
I am happy that you like it :) I still suggest to root your vacuum, even for fun of changing sound files
