### ISSUE TITLE
Which Models does this work with?

### ISSUE THREAD

**Issue by dpackham** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#23]
I have a Gen 1 Xiaomi that has lidar and room mapping but does not allow defining zones to clean/avoid.  that capability was introduced with Gen 2.

Will this allow me to add this functionality to my Gen 1?

**Comment by PiotrMachowski** [comment]
This card works with Gen1, but the problem with is is that sometimes it rotates map, which forces card recalibration. To avoid map rotation you have to use zoned cleaning instead of normal full cleanup (just mark whole house as a zone).

**Comment by dpackham** [comment]
ok so to avoid the map rotation i need a gen 2 which has zone cleaning?  is that correct?

**Comment by PiotrMachowski** [comment]
As far as I know both Gen1 (after some software update) and Gen2 have zone cleaning. With Gen2 you don't have to use the hack I have described above, as it has map saving mode.
