### ISSUE TITLE
Adjustment to RTL

### ISSUE THREAD

**Issue by tzagim** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#245]
### Checklist

- [X] I have updated the card to the latest version available
- [x] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

There is currently no Adjust of the card to the RTL languages.
attached images.

This can be solved by the following design changes for RTL:
```

.map-actions-list:
	margin-left: auto; -> margin-right: auto;

.modes-dropdown-menu-entry-button.selected
	border-top-left-radius -> border-top-right-radius

	border-bottom-left-radius -> border-bottom-right-radius

.map-zoom-icons
	direction: ltr

#toast
	padding-left: 30px -> padding-right: 30px
	direction: ltr


Switching between > icon="mdi:chevron-left" (< & >)
```
**LTR**
![LTR1](https://user-images.githubusercontent.com/2285958/145049551-a52a198e-a9f2-4254-b698-9102721a1aff.png)
![LTR2](https://user-images.githubusercontent.com/2285958/145049006-f96b1fdc-0408-4939-8962-3bc3ff6170b6.png)

**RTL**  (after the adjustments)
![RTL1](https://user-images.githubusercontent.com/2285958/145049042-ce8a7bc5-f934-471f-9576-2c7acc2e753d.png)
![RTL2](https://user-images.githubusercontent.com/2285958/145049061-5d2e7a50-fa76-43a7-b0cc-90154e4bc9b1.png)

### What version of a card has described problem?

2.0.8

### What vacuum model do you have problems with?

s7

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2021.11.5

### What type of installation are you running?

Home Assistant OS

**Comment by tzagim** [comment]
Adding LTR to to map zoom icons

**Comment by tzagim** [comment]
#250

**Comment by PiotrMachowski** [comment]
RTL language support fully working in v2.0.9
