### ISSUE TITLE
Doesnt work under Chrome or HA App

### ISSUE THREAD

**Issue by murraykessell** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#25]
Hi, Thanks for this card. It really is very clever. It seems to work fine under Edge, but when I used Chrome or the new Home Assistant App, I don't see any images. Just the Mode select part.
Any ideas as to what the issue may be ?

**Comment by PiotrMachowski** [comment]
Hi, are you sure that image is correct? It works perfectly fine in both Chrome and app in my case. Are there any errors in browsers console?

**Comment by murraykessell** [comment]
Sorry, you're right. I was trying to get around the HASS caching/refresh issues by changing the image name and ended up with an image that didn't exist. However it still continued to worked in Edge probably due to the image being cached ? , but wouldn't work on other devices that I hadn't used.  Sorry to have bothered you.

**Comment by PiotrMachowski** [comment]
No problem, I'm happy you got it working

**Comment by murraykessell** [comment]
Yeah me too. Thanks for this

**Comment by murraykessell** [comment]
Hi ya,

Just a suggestion you might want to consider.

The background of the floor plan of my house is white, so I had to change the colour of the Zoned Cleanup in the JS so I could see the box.

Maybe to make it easier for others you could make the colours an option Key that’s configurable from within Lovelace 

 

Thanks

**Comment by PiotrMachowski** [comment]
Hi,
Thanks for your suggestion, it is on my TODO list. Right now I work on live maps, so colours are waiting for me to finish.
