### ISSUE TITLE
Multiple cycles of room cleaning

### ISSUE THREAD

**Issue by thehijacker** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#256]
### Description

Sometimes I wish my vacuum cleaner to clean two rooms only. There are carpets in that rooms and I wish it to clean them twice or three times.

In Xiaomi Home you can, with selected room cleaning, choose how many cycles you wish it to clean. By default value is 1x but you can select also 2x or 3x cycles.

Here I can only select what room without how many cycles. Cycle count can only be selected with Zone Cleanup.

![image](https://user-images.githubusercontent.com/13857043/145632179-14fd79f4-4a5a-4370-a76d-994224376f40.png)

![image](https://user-images.githubusercontent.com/13857043/145632907-3de5fdaa-31ec-41c0-a6e2-ca030f45652c.png)

### Solution

Can you please add and option to select how many cycles you wish vacuum to do on selected rooms?

![image](https://user-images.githubusercontent.com/13857043/145633145-9f3fc306-5634-40d8-bbdf-2ab08da5faad.png)

Thank you.

**Comment by nkgiovannivl** [comment]
In my case:

map_modes:
  - template: vacuum_clean_segment
    repeats_type: EXTERNAL
    max_selections: 5
    max_repeats: 5
    
   
![image](https://user-images.githubusercontent.com/48342344/147897614-d4653c81-1553-4981-9804-955fa7c6c390.png)

**Comment by PiotrMachowski** [comment]
@nkgiovannivl it won't work

**Comment by PiotrMachowski** [comment]
Added in v2.0.9
