### ISSUE TITLE
Vacuum Map

### ISSUE THREAD

**Issue by DrmeddieWiese** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#26]
Hello,

i have integrated your custom card via hacs. But in my card is no map image only the drop-down menu. Do I have to create an own map image or does your py-code generate one?

Thanks.

**Comment by PiotrMachowski** [comment]
Hi,

as written in [documentation](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#faq), you have to create map by yourself.

**Comment by DrmeddieWiese** [comment]
Sorry. Things should be read to the end.
