### ISSUE TITLE
Format of date and time tile entities

### ISSUE THREAD

**Issue by new-kirte** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#275]
### Description

It would be nice to have a datetime format option for date and time entities, so they can be displayed as
![image](https://user-images.githubusercontent.com/10042655/147759804-cde4c5b5-cce5-4cde-b174-d372582a3e04.png)

instead of

![image](https://user-images.githubusercontent.com/10042655/147759829-b0a1e979-9945-40d5-b03e-890c45acc6b1.png)

And last but not least - thank you so mucjh for the lovely frontend!

### Solution

Add a datetime formatiing option

**Comment by Bellavista** [comment]
Hi i use a sensor tempalte to trasform the desiserate format in IT lenguage

sensor:
    cerchio_last_clean_end_formato_data_it:
      value_template: >-
        {% set today = states('sensor.cerchio_last_clean_end') %}
        {% set arr_week_days = ["Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab"] %}
        {% set arr_months = ["Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"] %}
        {% set week_day = as_timestamp( today, 0 ) | timestamp_custom('%w') | int %}
        {% set day = as_timestamp( today, 0 ) | timestamp_custom('%d') %}
        {% set month = as_timestamp( today, 0 ) | timestamp_custom('%m') | int %}
        {% set year = as_timestamp( today, 0 ) | timestamp_custom('%y') | int %}
        {{ arr_week_days[week_day] }} {{ day }} {{ arr_months[month-1] }} {{ year }}, {{ as_timestamp(states('sensor.cerchio_last_clean_end')) | timestamp_custom('%H:%M', 0) }}
![image](https://user-images.githubusercontent.com/46230198/148387998-8e662cec-5cd6-4f3a-9a29-9f14442cc8d0.png)

**Comment by PiotrMachowski** [comment]
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)
