### ISSUE TITLE
Change colors of button when reaching timeout

### ISSUE THREAD

**Issue by MisterTdog** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#284]
### Description

Hello, thank you for this wonderfull card !
Would it be possible to implement a way to define error level and color in the List entry parts?
So that sensors/filters/brushes icons & values could appears in red for example when reaching the maintenance delay.

### Solution

Be able to set a warning level with a warning color. (ex: orange)
Be able to set a error level with an error color. (ex: red)
When the sensor/filter/brush/etc reach down the warning/error level, then display the entity rectangle with level color.

**Comment by PiotrMachowski** [comment]
It's already possible to do it using [card mod](https://github.com/thomasloven/lovelace-card-mod): https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/243

**Comment by MisterTdog** [comment]
Thank you very much !
That's perfect :D
