### ISSUE TITLE
Theme simulator + theme config generator

### ISSUE THREAD

**Issue by Jese44** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#287]
### Description

Hey, i like to match my map into my theme and it's colors (dark theme and green accents) it'd be useful to have live simulator on map color i.e. on website which would generate color attributes that tou can copy to configuration file. I hope you got the idea i'm after

### Solution

Someone with skills and time could create simulator either web based  or app. I know the attributes are described in card manual, but if i want to see how the colour looks, it takes so many extra steps to actually see how it looks like compared to other areas of the map

**Comment by PiotrMachowski** [comment]
Card itself automatically adapts to your theme, are you talking about map itself?

**Comment by Jese44** [comment]
The map itself and the colors tou modify to the camera settings

**Comment by PiotrMachowski** [comment]
Updating map colors is pretty easy, you just need to set value in configuration file, call service `xiaomi_cloud_map_extractor.reload` and changes will be applied. I don't think it is really useful to create another tool to do it

**Comment by Jese44** [comment]
Oh, theres a service for that... I've done it in a hard way and restarted the HA everytime i changed color 😅 thanks for the tip, in that case no need for any tool.

**Comment by PiotrMachowski** [comment]
Yup, it is even visible in "Server controls": at the bottom there is a button to reload map extractor ;)

**Comment by sca075** [comment]
@rwjack yep the mqtt_vacuum_camera can edit the colours from the options and as well there is a menu for the rooms colours (that can be renamed with the rooms names if setup in the vacuum's). Anyhow for the card buttons (#666) is the correct point.
