### ISSUE TITLE
Templates get translated to the wrong service name (miio2)

### ISSUE THREAD

**Issue by M1Sandy** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#297]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

template like 'vacuum_clean_zone' get translated as 'vacuum_clean_zone'  which is not correct for miio2 users. 
miio2 create 'xiaomi_clean_zone' service

miio2 code: 
```
SERVICE_CLEAN_ZONE = "xiaomi_clean_zone"
SERVICE_CLEAN_POINT = "xiaomi_clean_point"
```

![image](https://user-images.githubusercontent.com/29939651/148811920-c31f8675-cce9-45e2-9ab8-fc0f51c80ade.png)
![image](https://user-images.githubusercontent.com/29939651/148811971-1a7872ce-8c5d-4291-b506-43e006685d68.png)

### What version of a card has described problem?

x2.0.9

### What vacuum model do you have problems with?

STYJ02YM

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

chrome

### What version of Home Assistant do you use?

core-2021.12.8

### What type of installation are you running?

Home Assistant OS

**Comment by PiotrMachowski** [comment]
Which `miio2` integration do you mean? There is like a million of them 😃

**Comment by M1Sandy** [comment]
my bad Im not using the supported one. sry
