### ISSUE TITLE
How to create map?

### ISSUE THREAD

**Issue by nickdos** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#3]
It's not clear to me from the README file, on how I go about creating the map png file. I'm also not clear on how that file is scaled WRT to the coordinates provided in the config. I.e how does it know to draw the "rooms" onto the map file so that they match the provided map image file.

**Comment by PiotrMachowski** [comment]
I have updated README with information about creating map.
Card uses coordinates of two points: `base_position` and `reference_point` to calculate rotation and scale that need to be applied to convert coordinates between coordinate systems.

**Comment by maxcalavera81** [comment]
Thank you so much for your excellent work, but I still couldn't understand how I can get the map coordinates I created. Can you give some more tips on how to get the coordinates of the image map?
Thanks a lot for the help.

**Comment by PiotrMachowski** [comment]
The simplest way to calibrate this card would be:
1. Send a vacuum to a point on the map (using FloleVac or service `vacuum.send_command` in HA with data:
`{
  "entity_id": "vacuum.roborock",
  "command":"app_zoned_clean",
  "params":[25500, 2500]
}`
2. Coordinates of this point have go to section `vacuum` in `calibration_points` section
3. Find coordinates of a corresponding point on a map image. These values should be set in `map` section.

Follow these steps 3 times for 3 different points (the bigger distances between them the better)

**Comment by maxcalavera81** [comment]
thank you, I already managed to configure the card.
nice work
