### ISSUE TITLE
Extract map from xiaomi vacuum cleaner

### ISSUE THREAD

**Issue by payano** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#31]
Hello,

How did you extract your map from the vacuum cleaner?
I can extract zones but I haven't found a way to extract the map of my apartment though.

BR,
Johan

**Comment by PiotrMachowski** [comment]
Hi Johan,

My map is a screenshot from Xiaomi Home application after some processing in Gimp.
If you have rooted your vacuum you can use live map, e.g. [Hypfer/ICantBelieveItsNotValetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo), [asphalter/xiaomi_vacuum](https://github.com/asphalter/xiaomi_vacuum) or [pheuzoune/ha_xiaomi_vacuum_map](https://github.com/pheuzoune/ha_xiaomi_vacuum_map).

Best regards,
Piotr

**Comment by Whazor** [comment]
There is a [java map viewer](https://community.openhab.org/t/xiaomi-vacuum-map-viewer-to-find-coordinates-for-zone-cleaning/103500) ([source](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java) and [file format](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/RRMapFile/RRFileFormat.md)) which also helps with finding the coordinates. To download the map I used OpenHAB, with Xiaomi MIIO bindings and putting it on debug mode. You can could download the map via the xiaomi cloud, the OpenHAB source code for connecting to the xiaomi cloud [here](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java) and the protocol for downloading the map is described [here](https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/map_v1.md). All code and documentation is thanks to @marcelrv.

**Comment by PiotrMachowski** [comment]
WOW, that is something I was waiting for! I will try to implement it in [map camera](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera)

**Comment by PiotrMachowski** [comment]
@Whazor I have implemented it [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)

**Comment by Whazor** [comment]
So fast! This is great! It is working very well for me.

**Comment by pznamenskii** [comment]
please consider adding a "select room to clean" mode as a feature request for this card - same as possible via the app.

**Comment by PiotrMachowski** [comment]
@pznamenskii there already is a [feature request](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/47) for this case
