### ISSUE TITLE
Small zoning issue on android new app

### ISSUE THREAD

**Issue by wimip** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#32]
In the responsive website, no issue at all but in the android app there is a displacement in preset zones.

Not tried to create zones within the app.

In the app:
![Screenshot_20191229-151722](https://user-images.githubusercontent.com/54082554/71557981-55970e00-2a4e-11ea-88b0-c1f5f69bf0e2.jpg)
 
In the website:
![Screenshot_20191229-151917](https://user-images.githubusercontent.com/54082554/71558002-9ee75d80-2a4e-11ea-8f9e-4e19678781b9.jpg)

As it's the only card that do not works for me, I submit this issue here, but perhaps it's a bug from the app itself.

**Comment by PiotrMachowski** [comment]
Hi,
Do zones align correctly after selecting one of them?
I have checked and in my case everything is working perfectly well (Galaxy S8, latest version of HA app)

**Comment by PiotrMachowski** [comment]
Does this issue still exist in the latest version of HA app?

**Comment by wimip** [comment]
Issue still here.
Does not align better when selected.
I will try to add a more simple view with only your card !
Thx for investigating in this 👍
![Screenshot_20200107-094651](https://user-images.githubusercontent.com/54082554/71881553-cd41f880-3132-11ea-8567-754f6f0ff44a.jpg)

**Comment by PiotrMachowski** [comment]
How does freehand zone work?

**Comment by wimip** [comment]
Drawed zones are corrects but I don't know if vacuum will use good coordinates.
Btw I enable the swipe to change view of cch and when I draw zone it brings me on another view.
Will try deactivate it.
Do you use cch ?

**Comment by PiotrMachowski** [comment]
I tried cch some time ago, but it was causing a lot of mess on my phone, so I ditched it. I have seen that it has been replaced with [custom-header](https://github.com/maykar/custom-header), so I plan to give it a try.
