### ISSUE TITLE
miot support

### ISSUE THREAD

**Issue by Zahy3100** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#356]
### Description

can you add https://github.com/al-one/hass-xiaomi-miot to support Xiaomi roidmi eve? I can't make it work with another platform

### Solution

Add miot platform

**Comment by PiotrMachowski** [comment]
I can't add it because it has a different data for every vacuum. You can configure it manually, like here: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/251
