### ISSUE TITLE
Card in browser_mod-pop up wrong position

### ISSUE THREAD

**Issue by Kejszijo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#39]
Hi,

This card does not always center, if I use it in browser_mod-pop-up window.  (90% of attempts are bad)

Good view:
![good](https://user-images.githubusercontent.com/13425330/72832165-9f0cfe80-3c84-11ea-999c-f6d472c9714d.jpg)

Wrong view:
![wrong](https://user-images.githubusercontent.com/13425330/72832168-a3391c00-3c84-11ea-8316-cd6b1bddee83.jpg)

**Comment by PiotrMachowski** [comment]
The problem is on browser_mod side, as its popups are unable to adjust to dynamic size of a card inside of it (the same issue exists for e.g. https://github.com/ljmerza/calendar-card)

**Comment by Kejszijo** [comment]
Ok, thanks.
