### ISSUE TITLE
Try to use clean zone with Lydsto R1

### ISSUE THREAD

**Issue by sagidam** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#393]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I am getting error message 
Vacuum clean zone service not found
What can i do to fix it?

### What version of a card has described problem?

v2.0.10

### What was the last working version card?

v2.0.10

### What vacuum model do you have problems with?

Lydsto r1

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome

### What version of Home Assistant do you use?

2022.5.2

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
Vacuum clean zone service not found
```

### Javascript errors shown in the browser's console (if applicable)

```shell
Vacuum clean zone service not found
```

**Comment by PiotrMachowski** [comment]
> ### Which integration do you use to control your vacuum (link)?
> https://www.home-assistant.io/integrations/xiaomi_miio/

I'm pretty sure that you don't use this integration. I suppose you have Xiaomi Miot Auto, am I right?


> ### Card's configuration
> ```yaml
> Vacuum clean zone service not found
> ```

Please provide card'a configuration

**Comment by sagidam** [comment]
You right...
I try to add this xiaomi miio but i get this error message on adding
integrartion
"
The device model is not known, not able to setup the device using config
flow."

**Comment by PiotrMachowski** [comment]
You have to check out this thread: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/251
