### ISSUE TITLE
Map size adjustment

### ISSUE THREAD

**Issue by talondnb** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#4]
I have a long house floorplan and when I import an image of my own of the full floorplan, it ends up being tiny on the screen within the card.

Is there a way to perhaps stretch this out to become larger?

![76204](https://user-images.githubusercontent.com/3942363/63520962-2a446580-c528-11e9-9bc6-19441f04d5f4.jpg)

**Comment by PiotrMachowski** [comment]
Size of image is defined by its original proportions and by size of the card. The only solution is to change one of them. In your case I would just rotate the image.
