### ISSUE TITLE
Add support for lovelace-swipe-navigation for better mobile experience

### ISSUE THREAD

**Issue by martkopecky** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#401]
### Description

Currenty, the card does not work with [Lovelace Swipe Navigation](https://github.com/maykar/lovelace-swipe-navigation) on mobile app (Android). You cannot swipe through layout views if your are swiping on top of the vacuum card. It is obviously because of the map scrolling feature which clashes with the swipe addon.

### Solution

Maybe the behavior could be improved slightly:

- Make swiping (swipe navigation) work if the map scrolling is locked
- Make swiping (swipe navigation) work if the map scrolling is set to require two fingers
- If there is a chance to make both map moving and swiping work, perfect

### Context

This is a nice-to-have feature, but would make the mobile experience slightly better.

**Comment by PiotrMachowski** [comment]
It has to be done in Lovelace Swipe Navigation itself, not in this card. You can check out this issue:
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/325
