### ISSUE TITLE
[Feature suggestion] Valetudo coordinates calculation switch

### ISSUE THREAD

**Issue by pejotigrek** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#41]
cześć! dzięki za kawał dobrej roboty! mam małą sugestię - opiszę po angielsku, żeby reszta internetu wiedziała o co chodzi ;)

ok, so I'm playing with your card since yesterday, and while I got it running nicely with my valetudo-rooted gen1 xiaomi vacuum robot, I was stuck for some time with coordinates calibration, just to find out that valetudo does something with y-axis, as it's mentioned numerous times even in your repo. that gave me an idea.

what if you'd add a switch, let's say `valetudo_fix` or even something shorter like `y_fix`, with _**false**_ being it's default option [if omitted], and **_true_** to get your card know it has to substract Y-coordinates from 51200 to undo "the valetudo magic". I know, it's not that hard to calculate it by ourselves, but that would speed up calibration process & also foolproof it for newer users :)
having it _false_ by default won't make a breaking change [I think].

is it plausible?

**Comment by PiotrMachowski** [comment]
Hi,
Thanks for your suggestion, it surely can improve calibration process.

Currently I am in the process of developing and testing a new version of card that will support rooted vacuums without calibration at all. You can check it out here: [map camera](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera) (but it hasn't been tested with gen 1 yet).

**Comment by pejotigrek** [comment]
sounds awesome! I'll add the new one to my list & will try to test this it only I'll manage to end my current configuration fixes.

but if I understand correctly - that would "download" the map from vacuum, right? so we won't be able to use our own pictures? now, as I'm starting to use your card with my home visuals it would be sad for me to loose current interface ;D

![image](https://user-images.githubusercontent.com/10796588/73136252-c3cdf100-404b-11ea-890e-27e778e6b305.png)

my _dream vacuum config_ is the card that displays my custom image as map background, and then - thanks to calibration - overlays only vacuum, docking station & current cleaning path [with colour settings for path and icon size/color for the rest]. but I know it's probably a pain to implement, so I'm just thinking out loudly ;)

**Comment by PiotrMachowski** [comment]
Wow, it looks really nice :)

Right now it is not possible to set up your own background, but it shouldn't be hard to add ;)

**Comment by pejotigrek** [comment]
thanks!

so I'll keep my eye on it, for sure! :)
