### ISSUE TITLE
Map Selection

### ISSUE THREAD

**Issue by cataseven** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#452]
### Description

For example; I have 4 different maps.

Upstairs, downstairs, Garage etc.. Can you please add support to select map? 

### Solution

Select map from map list.

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/444#discussioncomment-3208751
