### ISSUE TITLE
Enhancement Request - Add Cleaning Mode

### ISSUE THREAD

**Issue by IanAdd** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#46]
My Robovac does not detect my new rug as a carpet and hence does not speed up the fan automatically. Any chance of adding the 'Cleaning Mode' to the UI as available in the Mi Home app.
If that could be done then I would like any of the following options - if practical !
1) Set any of the user pre-defined zones to be a chosen Mode.
2) Mark a zone and choose the Mode to clean with.
2) Allow user to set default Mode
3) Set an area to be 'Max' and trigger Max on/off on entry/exit that area whilst in a clean. ?
In hope !

**Comment by IanAdd** [comment]
My S50 attribute list in HA shows five fan speed modes. It would be nice to be able to run one of the quieter modes at night.

**Comment by mced76** [comment]
Hello. 
With miio action is it possible to use the cleaning mode ?  
"[[selection]]", "[[repeats]]" are exposed but not cleaning mode. Is it possible to publish the selected cleaning mode into a var ?

**Comment by PiotrMachowski** [comment]
@mced76 what do you mean as cleaning mode? An additional field e.g. in icons?

**Comment by mced76** [comment]
cleaning mode = "fan speed mode" selected by the user
