### ISSUE TITLE
Add Tasshack/dreame-vacuum platform

### ISSUE THREAD

**Issue by Tasshack** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#493]
### Integration repository

https://github.com/Tasshack/dreame-vacuum

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

<a href="https://github.com/Tasshack/dreame-vacuum/blob/master/docs/entities.md">Entities</a>

### Service calls

<a href="https://github.com/Tasshack/dreame-vacuum/blob/master/docs/services.md">Services</a>

### Other info

I have already made the required changes. I am creating this issue just to link it with the pull request.

**Comment by thebiff999** [comment]
Is the feature "Going to point" necessary for a merge? I just stumbled upon this and would be happy to use these awesome cards in my Home Assistant Setup with Tasshack's Dreame Integration. I could also look into that feature if help is needed.

**Comment by PiotrMachowski** [comment]
@thebiff999, no, it's not necessary. I will merge it soon

**Comment by xBourner** [comment]
@PiotrMachowski is there an ETA for the next release so the dreame integration can be used?
@Tasshack do you share some beta access to test this?

**Comment by xBourner** [comment]
@PiotrMachowski thanks for the answer. i am getting the error:

`missed comma between flow collection entries (2:2)

 1 | {# ----------------- PROVIDE YOUR ...
 2 | {% set camera_entity = "camera." %}
------^
 3 | {% set vacuum_entity = "vacuum." %}
 4 | {# ------------------- DO NOT CHA ...`

seems like templates are not allowed. do i need anything to enable this?
i tried to add the code to your custom card.

**Comment by PiotrMachowski** [comment]
@xBourner step by step guide is available [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317) in section ”Adding rooms before v2.1.0” (just remember to use a template from dreame-vacuum repo

**Comment by PiotrMachowski** [comment]
@Tasshack One more thing: your PR has added tiles using attributes of vacuum entity. Do you plan to add support for [attribute translations](https://rc.home-assistant.io/blog/2023/03/29/release-20234/#more-translations) to your integration?

**Comment by PiotrMachowski** [comment]
@Tasshack I've asked about it because I have already added support for using integration's translations to the card (both states and attributes). If you plan to add translations to attributes then the card will be able to use them as well. In the other case I think it would be better to use dedicated entities instead. Additional benefit of using entities is that they will be translated even in earlier HA versions.

**Comment by PiotrMachowski** [comment]
@Tasshack which entities have this problem? It's possible to use attributes just for these entities that return unavailable states

**Comment by PiotrMachowski** [comment]
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)
