### ISSUE TITLE
Problem with the Installation

### ISSUE THREAD

**Issue by Judocrafter** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#51]
Hi
Sorry I am new to this area and need some help.

I did everything as described. I have entered the resources in the configuration.yaml. However, I always get the message Custom element doesn't exist: xiaomi-vacuum-map-card. Can you help me please?

![image](https://user-images.githubusercontent.com/42749857/88188577-584e9000-cc38-11ea-8f99-fd0cc9e9d543.png)
![image](https://user-images.githubusercontent.com/42749857/88188597-5d134400-cc38-11ea-8390-75247268028c.png)

**Comment by PiotrMachowski** [comment]
Hi!

The easiest way to install this card is to use [HACS](https://hacs.xyz/).
If you insist on doing it manually you should use following url:
```local/custome_lovelace/...```
 (are you sure it its not `custom` instead of `custome`?).
