### ISSUE TITLE
Exclude from zone

### ISSUE THREAD

**Issue by eMeF1** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#517]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [ ] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
n/a
```

### Service calls

```yaml
n/a
```

### Other info

It would be great to have the option to exclude the specific area that is placed in the middle of the zone e.g., a carpet that the robot cannot handle.
Similar to the no-go-zone but specific for the custom zone.

**Comment by PiotrMachowski** [comment]
It's not possible to achieve this feature in the card, it has to be implemented in the vacuum itself
