### ISSUE TITLE
Add possiblity to disabl all controls (Just show map)

### ISSUE THREAD

**Issue by SaSa1983** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#537]
### Description

I'd like to be able to hide all controls and just show the map, so that no action can be performed from within the map

### Solution

As described, please add an option to show a readonly (zommable) map without any controls

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/162#discussioncomment-3098299
