### ISSUE TITLE
Integracja z STYJ02YM

### ISSUE THREAD

**Issue by tromarek1** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#56]
Czy jest możliwa integracja takiej interaktywnej mapy ze stytj02ym? Próbuję to zrobić, mam wgraną miio. Mogę tam wysyłać takie koordynaty sprzątania czy tylko nazwę pomieszczenia?

**Comment by PiotrMachowski** [comment]
Duplicate of #38
