### ISSUE TITLE
Neabot / Neakasa

### ISSUE THREAD

**Issue by zai-smart-home** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#568]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [ ] Zone cleaning (using 4 coordinates)
- [ ] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [ ] Others

### Vacuum entity/entities

```yaml
neabot / neakasa
```

### Service calls

```yaml
neabot / neakasa
```

### Other info

neabot / neakasa vacuum

**Comment by PiotrMachowski** [comment]
Please provide all necessary info. I'll reopen the issue after that.
