### ISSUE TITLE
Get map image from Valetudo PNG data

### ISSUE THREAD

**Issue by deam0n** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#579]
### Description

For the Hypfer/Valetudo platform, documentation states that we must use "I can't believe it's not Valetudo" in order to get the map image.
For HassOS user's running docker containers (at least on the same system) is not an option as HassOS detects "foreign" docker containers and puts HA as non compliant .

Easy way to get map image for Hypfer/valetudo platform.

### Solution

As stated in https://hass.valetudo.cloud/ Valetudo is providing an entity with a PNG with a zTXt chunk containing the ValetudoMap JSON.

this could be extracted by the card to display Valetudo map in a seemingly way and potentially the calibration coordinates as well:

map_source:
  camera: camera.valetudo_roborocks5_map_data

**Comment by PiotrMachowski** [comment]
It won't be done by the card itself, but in the Map Extractor

https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/pull/408
