### ISSUE TITLE
Question: Card dynamic elements styling

### ISSUE THREAD

**Issue by damyanor** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#58]
Hi,
great plugin, I've installed it for the first time lately and works like a charm, luckily I've done that before updating HA to v0.115. I have a question - is it possible to change colors of the elements like: predefined zone not-selected/selected (red/green), zone mark box (transparent white/gray) and - what is the most important for me - close/resize buttons (black)? I suppose it can't be done via card-mod plugin or similar? Maybe somewhere the js code but I am certain it would be overwritten after each update.

**Comment by PiotrMachowski** [comment]
It is on my "TODO" list, I will implement this in a next major version of a card.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
