### ISSUE TITLE
select preset

### ISSUE THREAD

**Issue by guensen0** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#580]
### Description

Hi,

perfect work! I have 3 presets in my vacuum card and if I selected one of the additional presets and go to another view and back the card automatically jumps back to the 1st preset (keeping the map and specific floor dependent button cards). In principle everything works, just the fact that the selection if not synchronized... for example, to get back to 1st preview, you have to go to another preview and back... kind of cosmetic issue, but still raising questions in family ;-)
I have a variable that defines which floor is loaded, so I could jump easily to the current tab, if there would be a option (or may I have overseen something?)

### Solution

option to select which preset should be shown...

**Comment by PiotrMachowski** [comment]
You can configure `conditions` section for every preset, will this resolve your problem?

**Comment by guensen0** [comment]
not really... as I understand that would allow to show the card page that is currently used, but how to go to another page then? Only option: 3 additional buttons that reset the variable, but the question is whether the card then reload?

**Comment by guensen0** [comment]
for the whole card?

**Comment by PiotrMachowski** [comment]
Part related to switching presets should be enough

**Comment by guensen0** [comment]
this is the main card:

cards:
          - type: custom:xiaomi-vacuum-map-card
            title: ''
            preset_name: EG
            entity: vacuum.roborock_s5_max
            activate_on_switch: true
            activate:
              service: script.vac_test
              service_data:
                map: '0'
            vacuum_platform: default
            map_locked: true
            ...

**Comment by guensen0** [comment]
the 2nd card:

	additional_presets:
              - preset_name: Obergeschoss (Vorn)
                entity: vacuum.roborock_s5_max
                activate_on_switch: true
                activate:
                  service: script.vac_test
                  service_data:
                    map: '2'
		map_source:
                  camera: camera.xiaomi_cloud_map_extractor

**Comment by guensen0** [comment]
that's the script that is called:

alias: Vac_Test
fields:
  map:
    description: Which Map to select
    example: 1
sequence:
  - service: vacuum.send_command
    data:
      command: load_multi_map
      params: "{{ map }}"
    target:
      device_id: xxxxxxx
  - service: python_script.set_state
    data:
      entity_id: sensor.vac_map
      state: "{{ map }}"
mode: single

**Comment by guensen0** [comment]
i call the script with map: 0 or 2 or 3 for the different floors
it loads the corresponding map and set the sensor.vac_map to the same value
That value is used for selection of buttons and scripts on the page
![e44203cfb5a4a9ca710ac6d7d2fb284add752dd3](https://user-images.githubusercontent.com/59560120/236016195-0e6a8fb3-71ec-45b0-9bcb-c1df0f661492.jpeg)

**Comment by PiotrMachowski** [comment]
Ok, at this moment my suggestion would be to add conditions to all 3 presets (including default one) and add 2 icons to every preset (to change a map to a different one).

**Comment by guensen0** [comment]
so far works well, but when I switch to an
<img width="1272" alt="Screenshot 2023-05-03 at 20 58 20" src="https://user-images.githubusercontent.com/59560120/236016764-3fbce421-e637-4fe0-835e-6894370553fb.png">
other view and back it is still shows the right floor, but the card is in 1st position.

**Comment by guensen0** [comment]
> Ok, at this moment my suggestion would be to add conditions to all 3 presets (including default one) and add 2 icons to every preset (to change a map to a different one).

but is the card updating automatically?

**Comment by guensen0** [comment]
ok... then I will try that next days... thanks for your time.

**Comment by guensen0** [comment]
works like a charm

<img width="1236" alt="Screenshot 2023-05-04 at 20 51 31" src="https://user-images.githubusercontent.com/59560120/236301270-dee76772-c1b4-47b5-8a58-f54f1e59202b.png">

**Comment by PiotrMachowski** [comment]
Looks good 👍
