### ISSUE TITLE
Native support for Roborock mopping options

### ISSUE THREAD

**Issue by znanywawa** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#587]
### Description

Hi,
 As new update of custom Roborock integration: https://github.com/humbertogontijo/homeassistant-roborock supports now ability to set mop intensity and mop mode, I think it would be great to add it to card.
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/62244838/d9bd8ba6-75c7-40ff-b3b2-397d76258d29)

### Solution

I would like to be able to set mopping settings on Map Card while mop is attached:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/62244838/9fd41e17-a6fd-474e-9c5c-755cf97669e3)

**Comment by PiotrMachowski** [comment]
Yes, this is something I have on my todo list, but at this moment icons are not generated per integration, so I need to make them platform-dependent first.

**Comment by doug144** [comment]
It does and it looks & works great. Thanks!

**Comment by PiotrMachowski** [comment]
Great, thank you!

**Comment by PiotrMachowski** [comment]
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)
