### ISSUE TITLE
MyNeato compatibility

### ISSUE THREAD

**Issue by mikkelsiggaard** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#593]
### Description

The MyNeato Home Assistant integration just [added a camera map](https://github.com/BenjaminPaap/home-assistant-myneato/pull/12 ). I've tested this with my Neato D9 and works great. 

However, I get the error message "Invalid calibration, please check your configuration" when configuring the card. 
<img width="989" alt="image" src="https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/23178730/fb2721b2-2dfb-4ea3-90fe-330479aed72b">

### Solution

As far as I get see, the problem is that there is no calibration options for using the MyNeato integration. 
I don't completely understand the architecture of this project (it being based on Xiaomi), so I might have misunderstood completely. 

So if not already possible, it would be great to see compatibility with the [MyNeato integration](https://github.com/BenjaminPaap/home-assistant-myneato). [Camera map functionality](https://github.com/BenjaminPaap/home-assistant-myneato/issues/7) has just been added.

**Comment by PiotrMachowski** [comment]
Could you try to follow [these steps](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/518#issuecomment-1457514919) to send me details about vacuum entities?

**Comment by PiotrMachowski** [comment]
It would be great if you were able to do it as soon as possible - I wanted to create a new release today.

**Comment by PiotrMachowski** [comment]
I think I have managed to add support for this integration without this data. You can test it by installing [v2.2.0-beta.7](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0-beta.7). 

> Is it just my default Home Assistant dashboard (already tried, but didn't give me a good result) or something more specific?

Yes, this script should work on an HA dashboard

**Comment by mikkelsiggaard** [comment]
I installed v2.2.0-beta.7 and restarted HA, but see no difference at all.

**Comment by PiotrMachowski** [comment]
Have you cleared the cache and selected an appropriate vacuum platform?

**Comment by mikkelsiggaard** [comment]
That is my second part of this issue: There is support for the [Neato](https://www.home-assistant.io/integrations/neato) integration, but not the [MyNeato](https://github.com/BenjaminPaap/home-assistant-myneato) integration. 
So I can't select the appropriate vacuum platform. 

I am currently using the MyNeato integration, since I don't have the option to use the Neato integration.

**Comment by PiotrMachowski** [comment]
I suspect that it will work after cleaning cache. You can try incognito mode as well.

**Comment by PiotrMachowski** [comment]
Done in [v2.2.0](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/releases/tag/v2.2.0)
