### ISSUE TITLE
 question: the map is flipped

### ISSUE THREAD

**Issue by olegosipenko87** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#60]
Hi
The map is randomly drawn (flipped) when the vacuum cleaner is running. Сoordinates get lost because of this.
how to make the vacuum cleaner draw the same map?

PS по русски ?

**Comment by PiotrMachowski** [comment]
Hi,
That is a problem of first Xiaomi vacuum, there's nothing that can be done in the card itself.
To keep map orientation you can use zoned cleaning instead of normal one.

PS Tylko po angielsku albo po polsku ;)
