### ISSUE TITLE
divider in tiles beside the multiplier

### ISSUE THREAD

**Issue by WarLL3** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#603]
### Description

It would be nice to have a divider beside the multiplier in the tiles attributes. My statistics and consumables are shown in minutes or seconds.

### Solution

Add divider attribute to the tiles.

**Comment by PiotrMachowski** [comment]
Just set multiplier to 1/divider: `divider: 5` -> `multiplier: 0.2`
