### ISSUE TITLE
support for iLife T10

### ISSUE THREAD

**Issue by VipulRSI** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#613]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [X] Going to point (using 2 coordinates)
- [X] Cleaning a point (using 2 coordinates)
- [ ] Others

### Checklist

- [ ] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
iLife T10
```

### Service calls

```yaml
iLife T10
```

**Comment by PiotrMachowski** [comment]
How do you expect me to implement anything when you provided absolutely no information about the vacuum?
