### ISSUE TITLE
Adjust to Xiaomi cloud map extractor

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#62]
Utilize features available in [Xiaomi cloud map extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)

**Comment by PiotrMachowski** [comment]
Added attribute in [Xiaomi Cloud Map Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor) that contains configuration of `calibration_points`: [documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#attributes-configuration).

**Comment by pznamenskii** [comment]
a bit unclear how to use it though.
tried as:

      - calibration_points:
          - camera.vaccum_map.calibration_points
        map_camera: camera.vaccum_map

but getting

Exactly 3 calibration_points required
calibration_points:
  - camera.vaccum_map.calibration_points
debug: false
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.vaccum_map
camera_refresh_interval: 1
type: 'custom:xiaomi-vacuum-map-card'

**Comment by PiotrMachowski** [comment]
@pznamenskii Right now you have to manually copy these points to card's configuration. In future versions of a card it will be done automagically :)

**Comment by pznamenskii** [comment]
I see, but where do I get the values of the attribute from?
calibration_points in not seen under vaccuum_m,ap entity under developer section unlike all the other attributes, though I asked for it:

    attributes:
      - calibration_points
      - charger
      - goto
#      - goto_path
#      - goto_predicted_path
      - image
      - no_go_areas
      - no_mopping_areas
      - obstacles
#      - path
      - vacuum_position
      - walls
      - zones

btw, all those I did not ask for and commented out are still present bringing the long scroll headache back

**Comment by PiotrMachowski** [comment]
@pznamenskii you have to have the latest version of extractor for this feature to work. After installation you have to restart HA

**Comment by pznamenskii** [comment]
> @pznamenskii you have to have the latest version of extractor for this feature to work. After installation you have to restart HA

of course - I updated the code, removed the cache and restarted HA before editing cfg for new values - HA would not validate config with the old code, btw - as the attributes were not listed in the old code.

**Comment by PiotrMachowski** [comment]
There must be something wrong with your configuration, can you show it here?

**Comment by pznamenskii** [comment]
> There must be something wrong with your configuration, can you show it here?

[cameras.txt](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/5317951/cameras.txt)

**Comment by pznamenskii** [comment]
and states dump from dev tools in HA
[states_dump.txt](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/files/5317969/states_dump.txt)

**Comment by PiotrMachowski** [comment]
Are you sure all integration's files are up-to-date?

**Comment by pznamenskii** [comment]
> Are you sure all integration's files are up-to-date?

pretty much
![ls](https://user-images.githubusercontent.com/1525291/94924922-14dd9100-04c7-11eb-8bd1-26271f746705.png)

**Comment by pznamenskii** [comment]
wiped out the dir, re-downloaded and restarted HA - all good now

calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 30
      'y': 230
  - vacuum:
      x: 26500
      'y': 25500
    map:
      x: 70
      'y': 230
  - vacuum:
      x: 26500
      'y': 26500
    map:
      x: 70
      'y': 190

sorry for wasting the time and thanks for help

**Comment by PiotrMachowski** [comment]
No problem, I am happy you got this working

**Comment by PiotrMachowski** [comment]
You can now enable automatic calibration by adding `camera_calibration: true` in config.

**Comment by r3dsouza** [comment]
Thanks for adding this feature! Really like it.

Along the same lines as this, would it also be possible to add the functionality where the card's `zones` derives it's coordinates from the `rooms` attribute of the Xiaomi Cloud Map Extractor entity. This would be such a great addition since the zones this would mean that when the vacuum changes from one level to another, the rooms are mapped automatically.

**Comment by oakhill87** [comment]
> 
> 
> You can now enable automatic calibration by adding `camera_calibration: true` in config.

I have tried this, but I still have to add a "calibration_points" section, and copy the attributes to the same file. Is this how it is supposed to be?

**Comment by PiotrMachowski** [comment]
@oakhill87 nooo, you don't have to add `calibration_points`

**Comment by oakhill87** [comment]
![image](https://user-images.githubusercontent.com/43674572/111887828-ecdfdc80-89d7-11eb-9c85-845536600e08.png)

Here's what happens when I don't use `calibration_points:`

**Comment by sheminasalam** [comment]
I am having the same issue, did you solve it?

> ![image](https://user-images.githubusercontent.com/43674572/111887828-ecdfdc80-89d7-11eb-9c85-845536600e08.png)
> 
> Here's what happens when I don't use `calibration_points:`

**Comment by PiotrMachowski** [comment]
No, for now just pass 
```
calibration_points: null
```

**Comment by sheminasalam** [comment]
I tried that but still for some reason its not going through. i get this response.
![image](https://user-images.githubusercontent.com/45196177/123608142-236d9480-d81c-11eb-9e62-7acf5ac3dd25.png)

**Comment by PiotrMachowski** [comment]
Can you try?
```
calibration_points: true
```

**Comment by sheminasalam** [comment]
Still not working.
![image](https://user-images.githubusercontent.com/45196177/123617515-f4a7ec00-d824-11eb-822b-4fe72f0265c4.png)

**Comment by sheminasalam** [comment]
Now its working with the above configuration

**Comment by sheminasalam** [comment]
It broke again.

**Comment by zivgin** [comment]
> It broke again.

same here
It doesn't work if i remove the "calibration_points"
and it doesn't work if i change the value to true \ false \ null either

**Comment by aaa-hu** [comment]
please tell me how to add cards to lovelace ???

**Comment by PiotrMachowski** [comment]
@aaa-hu https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
