### ISSUE TITLE
Extend service_call_schema to allow multiple service calls

### ISSUE THREAD

**Issue by bfg100k** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#623]
### Description

Some vacuums like the Viomi series requires 2 service calls for the Zone and Point cleaning. [example here with current workaround](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/406#discussioncomment-3694847). 

### Solution

Is it possible to extend the service_call_schema feature to allow more than 1 service call? Something like this?
    service_call_schema:
      service: xiaomi_miot.set_miot_property
      service_data:
        entity_id: '[[entity_id]]'
        siid: 6
        aiid: 5
        params:
          - piid: 2
            value: '[[selection_unwrapped]]'
      service: xiaomi_miot.call_action
      service_data:
        entity_id: '[[entity_id]]'
        siid: 6
        aiid: 1

**Comment by PiotrMachowski** [comment]
It's not a good idea to call multiple actions from the UI (to make sure they run sequentially), the best way to handle such situation is to create a script (like in the link you have attached)
