### ISSUE TITLE
Add and clarify the list of supported vacuum cleaners

### ISSUE THREAD

**Issue by Bagunda** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#624]
### Description

I still did not understand which vacuum cleaners to consider for purchase, in order to be supported by this excellent integration.
Does Roborock vacuum cleaner support? And which models?

### Solution

I would like a page with a list of vacuum cleaners.  And an explanation of how to choose vacuum cleaners to be supported by this integration

**Comment by PiotrMachowski** [comment]
This card is not vacuum-specific. It just communicates with integrations. To find supported vacuums you have to search individually for every [supported vacuum platform](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#supported-vacuum-platforms). I would advise to use something that works with Xiaomi Miio, Roborock, Dreame or Valetudo/Valetudo RE.

**Comment by Bagunda** [comment]
I don't understand. Can you tell me? Is it possible to add a vacuum cleaner "xiaomi omni 1s" to the home assistant? I realized that you only have an interface. But I really want to buy a vacuum cleaner that will fit your interface.

**Comment by PiotrMachowski** [comment]
> Is it possible to add a vacuum cleaner "xiaomi omni 1s" to the home assistant?

I have no idea, there's a looooot of different Xiaomi vacuums and a lot of integrations that can be used to connect them to HA. Additionally often the same vacuums are sold using different names in different countries.

I have never heard the model you have mentioned, I think the best option right now are Roborocks
