### ISSUE TITLE
Here is Czech translate

### ISSUE THREAD

**Issue by matata86** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#63]
Can you implement please?
`"cs": {
        mode: "Mód",
        goToTarget: "Poslat na zvolený bod",
        zonedCleanup: "Úklid zóny",
        zones: "Zóny",
        run: "Start",
        repeats: "Opakovat:",
        confirmation: "Příkaz odeslán!"`

**Comment by PiotrMachowski** [comment]
Thanks, I have added your translations in v1.1.12
