### ISSUE TITLE
[Roborock] Possibility to start a defined program

### ISSUE THREAD

**Issue by Phoenix-DH** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#631]
### Description

In the roborock app you can define programs, ways on how the robo should clean room by room:
![IMG_5999](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/44058592/d1868570-aa16-4745-92e0-5d0d5aa7acb1)

Is there a way to implememt this in the integration?

Thanks.

### Solution

Possibilty to select in UI.

**Comment by PiotrMachowski** [comment]
This is a feature request you have to create in the integration that you use to control your vacuum

**Comment by Phoenix-DH** [comment]
Ok, thank you.
