### ISSUE TITLE
No map - Internal server error 500

### ISSUE THREAD

**Issue by HaunsTM** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#649]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Can't say when I saw this problem for the first time. I does not seem to be reported anyway, I have had it for a while now.

Normally I can see a drawing map here:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/10531742/73dc955e-71ae-46bc-acbe-7b4f39c98a35)

In logs, I have this output:
![image](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/10531742/21e56ed6-fb84-4073-96e2-65354458f8e5)

```
This error originated from a custom integration.

Logger: custom_components.dreame_vacuum.dreame.map
Source: custom_components/dreame_vacuum/dreame/map.py:3769
Integration: Dreame Vacuum (documentation, issues)
First occurred: 06:13:34 (2 occurrences)
Last logged: 06:13:36

Map render Failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3744, in render_map image = self.render_objects( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 3938, in render_objects self._layers[MapRendererLayer.SEGMENTS][k] = self.render_segment( ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/map.py", line 4624, in render_segment tw, th = draw.textsize(text, text_font) ^^^^^^^^^^^^^ AttributeError: 'ImageDraw' object has no attribute 'textsize'
```

### What version of a card has described problem?

 v2.2.2

### What vacuum model do you have problems with?

Dreame D10s Plus

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Chrome 116 (Win 11)

### What version of Home Assistant do you use?

2023.8.3

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
-
```

**Comment by PiotrMachowski** [comment]
https://github.com/Tasshack/dreame-vacuum/issues/166
