### ISSUE TITLE
Wrong zone draw

### ISSUE THREAD

**Issue by WMP** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#65]
To draw a zone i use debug option, but after restart the zone is bigger that i draw. I record video: https://streamable.com/46432t

**Comment by PiotrMachowski** [comment]
That is super weird... Can you share your config?

**Comment by WMP** [comment]
Of course:

```
resources:
  - url: /local/vacuum-card.js
    type: module
  - url: /local/custom_lovelace/xiaomi_vacuum_map_card/xiaomi-vacuum-map-card.js
    type: module
title: Dom
views:
  - title: Odkurzanie
    cards:
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.stefan
        title: Gora
        map_image: '/local/custom_lovelace/xiaomi_vacuum_map_card/map_gora.png'
        calibration_points:
          - vacuum:
              x: 27993
              y: 30023
            map:
              x: 1046
              y: 61
          - vacuum:
              x: 18493
              y: 30023
            map:
              x: 103
              y: 62
          - vacuum:
              x: 27993
              y: 22073
            map:
              x: 622
              y: 569
        languange: pl
        debug: true
        zones:
          - [[21960,25892,30338,30649]]
```

And map file: https://imgur.com/a/jO6fbF5

**Comment by WMP** [comment]
Do you have any idea how can i help you to debug this?

**Comment by PiotrMachowski** [comment]
Sorry, I forgot about this issue. I will try to reproduce it on my instance

**Comment by WMP** [comment]
Now i want to clean in selected zone: 
![image](https://user-images.githubusercontent.com/45381/96709930-a5f3a980-139b-11eb-9962-ef3fa15f1e1e.png)
but my roborock start cleaning whole flor, but told over speaker about start zone cleaning.

**Comment by PiotrMachowski** [comment]
Ok, I have found a problem: `map` coordinates for last calibration point are invalid.
You can see that `vacuum.x` value is the same in 1st and 3rd point, so they should be on a vertical line

**Comment by PiotrMachowski** [comment]
You can check out [Map Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor), it will provide a live map view and a calibration

**Comment by PiotrMachowski** [comment]
I will try to create a version for rooted devices later :)
