### ISSUE TITLE
Websocket command entity/source is changed in Home Assistant Core 2023.10

### ISSUE THREAD

**Issue by emontnemery** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#656]
### Description

Websocket command entity/source is changed in Home Assistant Core 2023.10, and now provides much less information, for details see the [dev blog post](https://developers.home-assistant.io/blog/2023/09/12/ws-entity-source-simplified).

lovelace-xiaomi-vacuum-map-card uses it here: https://github.com/Rittsel/lovelace-xiaomi-vacuum-map-card/blob/0b6aa16d13ac483a5a2b21ba5442b5da4ddc813e/src/utils.ts#L159-L164 and needs to be updated.

### Solution

Config entry id is present in entity registry, use that instead of `entity/source `

**Comment by PiotrMachowski** [comment]
Thank you for the heads-up, but the fork you have linked is outdated, my version already uses entity registry: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/228348622c196c4e6676e848f58f76e2e71f3d81/src/utils.ts#L234
