### ISSUE TITLE
No Camera to select for Roborock Q8 Max

### ISSUE THREAD

**Issue by philharmonie** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#663]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I added the roborock integration and got my `vacuum.roborock_q8_max` entity but when I add the map card through HACS, I can't select the camera, as there is none.

### What version of a card has described problem?

v2.2.2

### What was the last working version card?

none

### What vacuum model do you have problems with?

vacuum.roborock_q8_max

### Which integration do you use to control your vacuum (link)?

https://www.home-assistant.io/integrations/xiaomi_miio/

### What browser (browsers/apps) does have this problem?

Sadaro

### What version of Home Assistant do you use?

Home Assistant 2023.8.4

### What type of installation are you running?

Home Assistant Container

### Card's configuration

```yaml
Not possible to create as I can't select the camera
```

**Comment by PiotrMachowski** [comment]
Well, you have to create a camera first, this is just a card

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
