### ISSUE TITLE
The websocket command 'camera_thumbnail' has been deprecated

### ISSUE THREAD

**Issue by monotonus** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#67]
Everytime I view my lovelace dashboard containing this card I get this message in my home assistant log:

The websocket command 'camera_thumbnail' has been deprecated

I'm running HA core 0.116.2

**Comment by monotonus** [comment]
I've forgotten to mention that I'm using map_camera together with the cloud map extractor.

**Comment by PiotrMachowski** [comment]
It will appear for every camera

**Comment by Enzokot** [comment]
Same here

**Comment by poisondima** [comment]
I get same message in log

**Comment by PiotrMachowski** [comment]
Everybody gets it :)

**Comment by smhgit** [comment]
me 2 :-)

**Comment by ioannispelelis** [comment]
Same here i am getting a lot of these warnings ever since i added xiaomi_cloud_map_extractor

**Comment by D34DC3N73R** [comment]
> It will appear for every camera

The cloud map extractor is the only camera that generates this message for me.

**Comment by ioannispelelis** [comment]
> > It will appear for every camera
> 
> The cloud map extractor is the only camera that generates this message for me.

Yes i can concur i have a regular camera configured as well and this warning never showed up until i install "xiaomi vacuum map card"

**Comment by PiotrMachowski** [comment]
It is generated by a card. It will appear for every camera that would be configured in this card.

**Comment by D34DC3N73R** [comment]
Ok, I guess I mean that I only get this error from this vacuum map card. None of my other camera cards generate this error.

**Comment by noorbertt** [comment]
I got a same warning. It's okay, just ignore it?

**Comment by PiotrMachowski** [comment]
It will be fixed someday ;)

**Comment by Nicols07** [comment]
Maybe this can help you for solve the bug 👍

([(https://github.com/resoai/TileBoard/issues/351)])

In this part of your code :

```
    updateCameraImage() {
        this._hass.callWS({
            type: 'camera_thumbnail',
            entity_id: this._config.map_camera,
        }).then(val => {
            const {content_type: contentType, content} = val;
            this.map_image = `data:${contentType};base64, ${content}`;
            if (this._config.camera_calibration) {
                if (!this._hass.states[this._config.map_camera].attributes.calibration_points) {
                    this.missingCameraAttribute = true;
                } else {
                    this.updateCoordinates(this._hass.states[this._config.map_camera].attributes)
                }
            }
            this.requestUpdate();
        })
    }
```

**Comment by pergolafabio** [comment]
yeah, tried it also, still happening here

**Comment by TTLucian** [comment]
Same issue here. Only camera type object I have is the vacuum map stuff

**Comment by Wibias** [comment]
Its getting spammed in the log now if you upgrade to beta 2021.3.0b0.

**Comment by PiotrMachowski** [comment]
@Wibias It has been spamming for quite some time. Has anything changed?

**Comment by Wibias** [comment]
Neeevermind. I have just overseen it. Also gets spammed with the stable version. Nevermind!

**Comment by canedje** [comment]
same messages over here.

**Comment by mcfly2283-ai** [comment]
Same here...

**Comment by lucidyan** [comment]
Same here. Unfortunately logs became unreadable with this message.

**Comment by lucidyan** [comment]
@pergolafabio Thanks for great advice!
I removed annoying messages by adding this block to `configuration.yaml`
```yaml
logger:
  default: info
  logs:
    homeassistant.components.camera: critical
```

**Comment by Enzokot** [comment]
ignoring errors in logs does not solve the initial problem

**Comment by Wibias** [comment]
https://github.com/custom-cards/surveillance-card/commit/1524fcbf95ff7e228ba3bc4c08bbfa5c018b825a

Fix on another component for that error message.

**Comment by alexander-saratovcev** [comment]
Hi, any updates here?

**Comment by PiotrMachowski** [comment]
@alexander-saratovcev I am rewriting the card form the scratch, which will fix this problem as well :)

**Comment by alexander-saratovcev** [comment]
> @alexander-saratovcev I am rewriting the card form the scratch, which will fix this problem as well :)

Good news, thank you!

**Comment by neforce** [comment]
> @alexander-saratovcev I am rewriting the card form the scratch, which will fix this problem as well :)

that would be nice. Because i've got a lottt of these messages :)

![image](https://user-images.githubusercontent.com/1107909/129920208-34dfde0c-bd54-47eb-8a3e-4a3797c18db8.png)

**Comment by PiotrMachowski** [comment]
@neforce it will take some time, I want to add a lot of features there :D

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
