### ISSUE TITLE
Tesvor X6

### ISSUE THREAD

**Issue by pbpromotion** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#676]
### Integration repository

https://www.home-assistant.io/integrations/xiaomi_miio/

### Supported features

- [X] Zone cleaning (using 4 coordinates)
- [X] Room cleaning (using room id/number)
- [ ] Going to point (using 2 coordinates)
- [ ] Cleaning a point (using 2 coordinates)
- [X] Others

### Checklist

- [ ] I have sent info about entities to `piotr.machowski.dev [at] gmail.com` ([Retrieving entities info](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/594); please provide your GitHub username in the email)

### Vacuum entity/entities

```yaml
dont know
```

### Service calls

```yaml
dont know
```

### Other info

where can i find this info?

**Comment by PiotrMachowski** [comment]
Does this vacuum work with Xiaomi Miio integration?

**Comment by pbpromotion** [comment]
i dont know, but i think not.

**Comment by PiotrMachowski** [comment]
> i dont know, but i think not.

Yeah, me neither. 

This card doesn't integrate any vacuum with HA. It just provides a nice way to control an already integrated vacuum, so you have to find the integration that will work with your model first.
