### ISSUE TITLE
Home assistant mobile app menus reload on map refresh.

### ISSUE THREAD

**Issue by cathelest** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#68]
There seems to be an issue with the map refresh on the android home assistant app.
It doesnt do it on a browser from the pc,
When the map refreshes the top bar and menus of home assistant reload. (see video) 
The refresh i have set in config is 5 seconds,

http://cathelest.com/vac.mp4

Phone is a samsung galaxy s20

Thanks again for such an awesome intergration.
Benjamin Malcolm

**Comment by PiotrMachowski** [comment]
This seems to be an issue with Home Assistant itself, there has been some problems with header in latest versions of HA
