### ISSUE TITLE
Dropdown menu in Chrome

### ISSUE THREAD

**Issue by AlexKash500** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#69]
Dropdown menu does not wotk in chrome
![image](https://user-images.githubusercontent.com/69472472/96370941-3e094d00-1168-11eb-84d1-79980c418bc9.png)

**Comment by PiotrMachowski** [comment]
It has been already fixed: #57

**Comment by AlexKash500** [comment]
I've reinstall card but same situation - no dropdown menu in Chrome. But It is working correctly in Opera. HomeAssistant - 0.116.4

**Comment by PiotrMachowski** [comment]
Do you use HACS?

**Comment by AlexKash500** [comment]
No I do not use HACS

**Comment by PiotrMachowski** [comment]
In this case it seems like a caching problem. Try adding `?v=1.1.12` to URL in resources.

**Comment by AlexKash500** [comment]
Yes. It is working. thanks
