### ISSUE TITLE
Rooting not needed

### ISSUE THREAD

**Issue by benleb** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#70]
...at least for my S6, the live map works without rooting...

FYI 👍

**Comment by etobi** [comment]
Could you share your `map_camera` configuration?

**Comment by benleb** [comment]
```
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum_cleaner
map_camera: camera.xiaomi_cloud_map_extractor
debug: false
calibration_points:
  - vacuum:
      x: 25500
      'y': 25500
    map:
      x: 58
      'y': 300
    ...
```

moved to https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues/28 (fits better there)

**Comment by etobi** [comment]
thanks for pointing me to the cloud-map-extractor

**Comment by PiotrMachowski** [comment]
I have updated README to point to [Extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)
