### ISSUE TITLE
Color of the "goto circle"

### ISSUE THREAD

**Issue by benleb** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#71]
Would be nice if the [color of the yellow circle](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/667d437a8ac5fef22951deeef7bd2c13e10387c6/dist/xiaomi-vacuum-map-card.js#L413) (the goto target point) can be customized too 👍

**Comment by PiotrMachowski** [comment]
I plan to make all colors configurable (like in the [map extractor](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)) 🙂

**Comment by darkkatarsis** [comment]
Good idea, E.g., the zone selection colors are similar to "no go zones" when turned on. You could also correct the "resize" and "close" icons because they seem to be a bit low resolution.

**Comment by PiotrMachowski** [comment]
@darkkatarsis They do not have a resolution, they just are a vector graphics drawn without anti-aliasing

**Comment by darkkatarsis** [comment]
Okay, I understand, then a color change might actually help when the background is also dark

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
