### ISSUE TITLE
Predefined "Tile list entry options"

### ISSUE THREAD

**Issue by 1andrevich** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#714]
### Description

I'm happy with almost the entire set of these tiles, but I want to remove a couple and add a couple without doing all this work from scratch. 

### Solution

Right now it's autogenerated or handmade tiles, predefined tiles or exclude list would be useful

**Comment by PiotrMachowski** [comment]
The easiest way to do it would be to click "generate static config" button, then go to YAML config and remove unwanted tiles
