### ISSUE TITLE
More and more "Rooms" entries in the dropdown list when creating a new "Xiaomi Vacuum Map Card" after change Roborock App Maps 

### ISSUE THREAD

**Issue by LHBL2003** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#728]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I have customized the rooms in the Roborockapp. Since then I get more and more "Rooms" entries in the dropdown list when creating a new "Xiaomi Vacuum Map Card". Every time I customize the room map in the Roborock app, there are more and more entries when generating.  

I have already uninstalled the HACS "humbertogontijo/homeassistant-roborock" and "Xiaomi Vacuum Map Card" and restarted HA properly. But the list does not get shorter when I create a new "Xiaomi Vacuum Map Card" and generate the rooms again.

The list for the living room is now so long that the map is no longer displayed.

![IMG_0026](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/46369917/4846d307-8954-4232-91ca-2b56e19ace30)

![IMG_0027](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/assets/46369917/85483299-0e89-42b5-ae10-ff15314f52ea)

### What version of a card has described problem?

V2.2.2

### What vacuum model do you have problems with?

roborock.vacuum.a27

### Which integration do you use to control your vacuum (link)?

https://github.com/humbertogontijo/homeassistant-roborock

### What browser (browsers/apps) does have this problem?

Safari,Google Chrome

### What version of Home Assistant do you use?

2024.4.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
Comment is too long (maximum is 65536 characters)
```

**Comment by PiotrMachowski** [comment]
Is a new entry created when you click "Generate rooms config"?

**Comment by LHBL2003** [comment]
No, if I repeat the generation, the number remains the same. 

But if I go into the Roborock app and change the map and initialise the Roborock HACK in HA. Then the number increases as soon as I recreate the map and generate it again.

I did the whole thing on an iPad Pro. I also deleted the browser cache. Now I have tried it on my MacBook Pro. The error does not occur there.

**Comment by LHBL2003** [comment]
Ok, it must be some kind of cache problem. I have now used incognito mode on the iPad Pro and don't have the problem there either. I made sure that I didn't just delete the cache for the last hour :D

**Comment by PiotrMachowski** [comment]
That's a weird caching error 👍

**Comment by LHBL2003** [comment]
It will probably be reproducible on an iPad Pro. I noticed this a few weeks ago. I almost didn't dare to create an artificial room for the hoover on the upper floor because I already had the problem on the ground floor :D
