### ISSUE TITLE
Can't configure the card

### ISSUE THREAD

**Issue by sciaio** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#75]
Hi!
I'm pretty new to HA
I installed through HACS and then rebooted.
When I try yo configure the card this shows up:
![image](https://user-images.githubusercontent.com/40140005/97604794-2a829f80-1a0e-11eb-8372-5f7e1e7b2ea4.png)
 

In the HACS Fronted section is installed:
![image](https://user-images.githubusercontent.com/40140005/97604909-500fa900-1a0e-11eb-9135-e2ea18d4ef79.png)

and also in resources is present:
![image](https://user-images.githubusercontent.com/40140005/97604961-5ef65b80-1a0e-11eb-9b1b-3c731dd88276.png)

What do I do in the wrong way?

Thank you

**Comment by PiotrMachowski** [comment]
Hi,
I have removed confusing part in documentation (it contained configuration of a whole view including this card).
You can check out updated [README](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#example-usage)
