### ISSUE TITLE
Roborock Q5 (Xiaomi) integration?

### ISSUE THREAD

**Issue by Reachushere** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#762]
### Description

I have the Roborock Q5, which works with my Xiaomi integration.  Will this work with your card?  I've been trying it but haven't managed to get it working so I am not sure if it requires specific integration or if the Xaiomi integration your card uses should work with my vacuum?

### Solution

To be able to use the card with the Roborock Q5

### Alternatives

To be able to use the card with the Roborock Q5

**Comment by PiotrMachowski** [comment]
Have you tried https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/?
