### ISSUE TITLE
Show error in card when vacuum gets stuck or runs into error

### ISSUE THREAD

**Issue by carefulcomputer** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#776]
### Description

Currently when vacuum gets stuck , the card doesn't show any error. So it is hard to know that it got stuck. 

### Solution

It will be nice for card to show the error and last known position prominently. That will allow for quick rescue of the bot.

**Comment by sca075** [comment]
@carefulcomputer this looks to be a good point I could add an event to notify the card (this also can be used with a script to create a notification to the mobile), and whenever the vacuum is in "error" condition create a repair notification in HA.

@PiotrMachowski I think probably this can be handled by my integration, anyhow I will post here if you want to add this to the card too the event name.

**Comment by PiotrMachowski** [comment]
For Xiaomi Miio as far as I remember vacuum entity has a possible `error` state. In such situation an additional `error` attribute is also available - it should contain a description of an error. 

I think that approach with an entity (either a state of vacuum entity or a dedicated one) would be more useful. A repair can also be created additionally.

@carefulcomputer which integration do you use?

**Comment by carefulcomputer** [comment]
@PiotrMachowski , I use valetudo .

**Comment by sca075** [comment]
> Does any entity report error status?

No Piotr Valetudo does not send error stat but the camera detects the error stats, I can also implement an event valetudo_error so that the card or the user can trigger an action.

**Comment by carefulcomputer** [comment]
there is a mqtt message sent from valetudo on error. Don't know if entity carries the error state. will check during holidays.

**Comment by carefulcomputer** [comment]
that will be great. few suggestions to make it even better (not sure what all is possible)-
1. Provide a slight red tint to whole image (which would indicate the error)
2. If possible draw a circle or replace robot icon (or enlarge, different color etc) to make location of robot more prominent.

**Comment by sca075** [comment]
@PiotrMachowski I think you can close this I will open a future request on my project with the comment that @carefulcomputer made. Thanks to you guys for the hints.
