### ISSUE TITLE
Zones dont show in selector card ¿Why¿

### ISSUE THREAD

**Issue by d4icon** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#78]
Hi,

I am using this component to pull the map automatically.

Everything has apparently gone well, but in the mode selector of the card, the zones do not appear. Just "go to" and "clean"
Why?

**Comment by PiotrMachowski** [comment]
Have you configured them?

**Comment by d4icon** [comment]
> Have you configured them?

Map extractor?
Yes, of course
I conf card map and extractor.

My map show oki.

Config recommended, nothing more.

**Comment by PiotrMachowski** [comment]
In a card, not extractor

**Comment by d4icon** [comment]
> In a card, not extractor

My config in card:


![IMG_20201102_091600](https://user-images.githubusercontent.com/5176086/97844915-24314380-1cec-11eb-8135-2a00664e7e1a.jpg)

**Comment by PiotrMachowski** [comment]
Zones are not yet automatically taken from the camera, you have to configure them like [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card#example-usage).

You can follow the progress of integration with Extractor [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/62)
