### ISSUE TITLE
Using map_image AND map_calibration: true

### ISSUE THREAD

**Issue by vini59fr** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#79]
Hi

First, thank's for this amazing card! Works great.

Now, I'd like to use my personnal 2D plan, but can't get it work with the option "map_calibration: true"

Is there any way to use both options ?

**Comment by PiotrMachowski** [comment]
In the future I will add an option to draw paths over an image, but it will still require calibration.

It is not possible to use generic image without calibration. A view from extractor can be automatically calibrated because it retrieves calibration from Xiaomi cloud.
