### ISSUE TITLE
Valetudo

### ISSUE THREAD

**Issue by foXaCe** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#8]
hello, 

this card do not work with valetudo rooted version why ?

**Comment by PiotrMachowski** [comment]
There were an issue with long-press feature, could you check if the latest version is working?

**Comment by foXaCe** [comment]
"vacuum/xiaomi_clean_zone". Service not found

**Comment by PiotrMachowski** [comment]
How did you set up your vacuum? Do you have `vacuum.xiaomi_clean_zone`service in developer tools?

**Comment by foXaCe** [comment]
![Image 1](https://user-images.githubusercontent.com/290678/63938228-982ae880-ca64-11e9-9266-6ba1a2d1fbcc.jpg)

**Comment by PiotrMachowski** [comment]
This card uses `vacuum.xiaomi_clean_zone` service for zoned cleanup. Do you have a different way for using zoned cleanup from Home Assistant?

**Comment by foXaCe** [comment]
https://github.com/Hypfer/Valetudo/wiki/Home-Assistant-Integration

**Comment by PiotrMachowski** [comment]
Service `vacuum.send_command` is not well documented in HA documentation. If it works for non-rooted vacuums I will migrate this card to it

**Comment by foXaCe** [comment]
ok thank you

**Comment by PiotrMachowski** [comment]
You can check out the latest version, I have migrated service calls to use `vacuum.send_command`
