### ISSUE TITLE
Any way to zoom or change scale on the map ?

### ISSUE THREAD

**Issue by kbouh320** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#82]
Hello, 
First, thank you for your work, it's amazing!

I am looking for a way to zoom or change scale on the map ? With a good scale it would be more convinient for my familly to precisely select zones

I tried changing settings of Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor but it doesn't seem to reflect on the card.

Thank you

<img width="1023" alt="Capture d’écran 2020-12-09 à 14 41 13" src="https://user-images.githubusercontent.com/412706/101637140-a4a23d00-3a2c-11eb-911d-1e2f972d8f2c.png">

**Comment by PiotrMachowski** [comment]
These settings of extractor should work, have you tried them?
[documentation](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#map-transformation-configuration)

**Comment by kbouh320** [comment]
I was focusing on scale which does not seem to have any effect whatever the value (1.5, 2, 3, 20, 200 etc.)
I tried the trim one which works perfectly and generates a zoom in as a secondary effect.
Thank you!

<img width="1024" alt="Capture d’écran 2020-12-09 à 15 50 44" src="https://user-images.githubusercontent.com/412706/101645163-52feb000-3a36-11eb-81b8-d79a516b3ef7.png">

**Comment by PiotrMachowski** [comment]
Scale has an effect on a image size (you can see it in a popup) :)
