### ISSUE TITLE
Automatic zones from rooms attribute of Xiaomi Cloud Map Extractor

### ISSUE THREAD

**Issue by r3dsouza** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#83]
I really like the inclusion of the calibration points from the Xiaomi Cloud Map Extractor entity #62. Related to this and to #50, would it be possible to add the functionality for the card to utilise the `rooms` coordinates from the `Xiaomi Cloud Map Extractor` entity.

This would mean that when the vacuum detects that it is on a different level and switches to that map, the card not only has the right calibration coordinates automatically, but also is able to have the right coordinates for the zones based on the rooms coordinates from the `Xiaomi Cloud Map Extractor` entity.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
