### ISSUE TITLE
Color of predefined zones

### ISSUE THREAD

**Issue by Maximus97** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#84]
I think it should be possible to select the color of the predefined zones, both for when they are selected and when they are not selected. The red color kinda makes the map look hostile and hard to look at.

**Comment by Maximus97** [comment]
Until this gets added (if it does), how does one adjust it manually by changing the code? It should only be a single change since it is just a color change, am I correct?

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
