### ISSUE TITLE
Command Sent but nothing happens

### ISSUE THREAD

**Issue by popescunsergiu** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#87]
RoboRock S5
Map loaded successfully so it seems that creds are correct.

Issue:
Trying to move the vacuum cleaner to a location or to clean an area, I get "Command Sent" but nothing happens

This is my card configuration:

```
type: 'custom:xiaomi-vacuum-map-card'
entity: vacuum.xiaomi_vacuum
camera_calibration: true
map_camera: camera.my_roborock_camera
```

**Comment by PiotrMachowski** [comment]
Do you have anything in logs?

**Comment by popescunsergiu** [comment]
Thank you @PiotrMachowski 
Forgot about the logs. Fixed it. I had a misspelling in the entity name
