### ISSUE TITLE
Card breaks when lovelace/browser window is reloaded in Chromium (no fault in MS Edge or IE)

### ISSUE THREAD

**Issue by a94marbo** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#88]
Reloading a lovelace page with this card, breaks the menu and diables the start button.
Before reload:
![image](https://user-images.githubusercontent.com/39158765/104597578-c8812000-5675-11eb-95c3-68856cb6102f.png)

After reload:
![image](https://user-images.githubusercontent.com/39158765/104597681-e8b0df00-5675-11eb-9804-3ed2b79695b5.png)

Only happens in chromeium on linux and windows. MS Edge and IE works fine. Have not found any settings yest in Chrome/Chromium that resolves this.

**Comment by PiotrMachowski** [comment]
Handled in v2.0.0
