### ISSUE TITLE
Suggestion: Reconfigure zone when using Zoned cleanup

### ISSUE THREAD

**Issue by Maximus97** [PiotrMachowski/lovelace-xiaomi-vacuum-map-card#9]
First of all, thanks for this amazing card.

I think a good addition would be to make it possible to reconfigure zone after creating them like you can do in the app, instead of having to press "Remove last zone" and make a new one.

**Comment by PiotrMachowski** [comment]
I'm glad you like it!

What do you mean by reconfiguration?

**Comment by Maximus97** [comment]
![Screenshot_20190829-153559__01](https://user-images.githubusercontent.com/42326685/63945582-da0f5b00-ca73-11e9-9daa-c6c08ed666e8.jpg)
After creating this zone, I can move it around but not make it bigger/smaller.

**Comment by PiotrMachowski** [comment]
You can check out the latest version, I have migrated added possibility to remove and resize zones
![image](https://user-images.githubusercontent.com/6118709/64396236-459d8d80-d05d-11e9-948e-34b6159ad17a.png)

**Comment by Maximus97** [comment]
It's a bit hard to press the resize button and the X button on a tablet, could you make the hitboxes bigger than the actual buttons?
